package com.zkxh.demo.model.role;

import com.zkxh.demo.common.base.entity.BaseEntity;
import com.zkxh.demo.model.sys_menu_role.SysMenuRole;
import com.zkxh.demo.model.user.SysUser;

import java.util.List;

public class SysRole extends BaseEntity {

    private SysUser sysUser;

    private List<SysMenuRole> sysMenuRoleList;

    public List<SysMenuRole> getSysMenuRoleList() {
        return sysMenuRoleList;
    }

    public void setSysMenuRoleList(List<SysMenuRole> sysMenuRoleList) {
        this.sysMenuRoleList = sysMenuRoleList;
    }

    public SysUser getSysUser() {
        return sysUser;
    }

    public void setSysUser(SysUser sysUser) {
        this.sysUser = sysUser;
    }


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.sys_roleid
     *
     * @mbg.generated
     */
    private Integer sysRoleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.sys_rolename
     *
     * @mbg.generated
     */
    private String sysRolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.sys_roledesc
     *
     * @mbg.generated
     */
    private String sysRoledesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.enable
     *
     * @mbg.generated
     */
    private Boolean enable;

//    private List<SysMenu> sysMenuList;
//
//
//    public List<SysMenu> getSysMenuList() {
//        return sysMenuList;
//    }
//
//    public void setSysMenuList(List<SysMenu> sysMenuList) {
//        this.sysMenuList = sysMenuList;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.sys_roleid
     *
     * @return the value of sys_role.sys_roleid
     * @mbg.generated
     */
    public Integer getSysRoleid() {
        return sysRoleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.sys_roleid
     *
     * @param sysRoleid the value for sys_role.sys_roleid
     * @mbg.generated
     */
    public void setSysRoleid(Integer sysRoleid) {
        this.sysRoleid = sysRoleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.sys_rolename
     *
     * @return the value of sys_role.sys_rolename
     * @mbg.generated
     */
    public String getSysRolename() {
        return sysRolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.sys_rolename
     *
     * @param sysRolename the value for sys_role.sys_rolename
     * @mbg.generated
     */
    public void setSysRolename(String sysRolename) {
        this.sysRolename = sysRolename == null ? null : sysRolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.sys_roledesc
     *
     * @return the value of sys_role.sys_roledesc
     * @mbg.generated
     */
    public String getSysRoledesc() {
        return sysRoledesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.sys_roledesc
     *
     * @param sysRoledesc the value for sys_role.sys_roledesc
     * @mbg.generated
     */
    public void setSysRoledesc(String sysRoledesc) {
        this.sysRoledesc = sysRoledesc == null ? null : sysRoledesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.enable
     *
     * @return the value of sys_role.enable
     * @mbg.generated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.enable
     *
     * @param enable the value for sys_role.enable
     * @mbg.generated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }
}