package com.zkxh.demo.model.role;

import java.util.ArrayList;
import java.util.List;

public class SysRoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    public SysRoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSysRoleidIsNull() {
            addCriterion("sys_roleid is null");
            return (Criteria) this;
        }

        public Criteria andSysRoleidIsNotNull() {
            addCriterion("sys_roleid is not null");
            return (Criteria) this;
        }

        public Criteria andSysRoleidEqualTo(Integer value) {
            addCriterion("sys_roleid =", value, "sysRoleid");
            return (Criteria) this;
        }

        public Criteria andSysRoleidNotEqualTo(Integer value) {
            addCriterion("sys_roleid <>", value, "sysRoleid");
            return (Criteria) this;
        }

        public Criteria andSysRoleidGreaterThan(Integer value) {
            addCriterion("sys_roleid >", value, "sysRoleid");
            return (Criteria) this;
        }

        public Criteria andSysRoleidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sys_roleid >=", value, "sysRoleid");
            return (Criteria) this;
        }

        public Criteria andSysRoleidLessThan(Integer value) {
            addCriterion("sys_roleid <", value, "sysRoleid");
            return (Criteria) this;
        }

        public Criteria andSysRoleidLessThanOrEqualTo(Integer value) {
            addCriterion("sys_roleid <=", value, "sysRoleid");
            return (Criteria) this;
        }

        public Criteria andSysRoleidIn(List<Integer> values) {
            addCriterion("sys_roleid in", values, "sysRoleid");
            return (Criteria) this;
        }

        public Criteria andSysRoleidNotIn(List<Integer> values) {
            addCriterion("sys_roleid not in", values, "sysRoleid");
            return (Criteria) this;
        }

        public Criteria andSysRoleidBetween(Integer value1, Integer value2) {
            addCriterion("sys_roleid between", value1, value2, "sysRoleid");
            return (Criteria) this;
        }

        public Criteria andSysRoleidNotBetween(Integer value1, Integer value2) {
            addCriterion("sys_roleid not between", value1, value2, "sysRoleid");
            return (Criteria) this;
        }

        public Criteria andSysRolenameIsNull() {
            addCriterion("sys_rolename is null");
            return (Criteria) this;
        }

        public Criteria andSysRolenameIsNotNull() {
            addCriterion("sys_rolename is not null");
            return (Criteria) this;
        }

        public Criteria andSysRolenameEqualTo(String value) {
            addCriterion("sys_rolename =", value, "sysRolename");
            return (Criteria) this;
        }

        public Criteria andSysRolenameNotEqualTo(String value) {
            addCriterion("sys_rolename <>", value, "sysRolename");
            return (Criteria) this;
        }

        public Criteria andSysRolenameGreaterThan(String value) {
            addCriterion("sys_rolename >", value, "sysRolename");
            return (Criteria) this;
        }

        public Criteria andSysRolenameGreaterThanOrEqualTo(String value) {
            addCriterion("sys_rolename >=", value, "sysRolename");
            return (Criteria) this;
        }

        public Criteria andSysRolenameLessThan(String value) {
            addCriterion("sys_rolename <", value, "sysRolename");
            return (Criteria) this;
        }

        public Criteria andSysRolenameLessThanOrEqualTo(String value) {
            addCriterion("sys_rolename <=", value, "sysRolename");
            return (Criteria) this;
        }

        public Criteria andSysRolenameLike(String value) {
            addCriterion("sys_rolename like", value, "sysRolename");
            return (Criteria) this;
        }

        public Criteria andSysRolenameNotLike(String value) {
            addCriterion("sys_rolename not like", value, "sysRolename");
            return (Criteria) this;
        }

        public Criteria andSysRolenameIn(List<String> values) {
            addCriterion("sys_rolename in", values, "sysRolename");
            return (Criteria) this;
        }

        public Criteria andSysRolenameNotIn(List<String> values) {
            addCriterion("sys_rolename not in", values, "sysRolename");
            return (Criteria) this;
        }

        public Criteria andSysRolenameBetween(String value1, String value2) {
            addCriterion("sys_rolename between", value1, value2, "sysRolename");
            return (Criteria) this;
        }

        public Criteria andSysRolenameNotBetween(String value1, String value2) {
            addCriterion("sys_rolename not between", value1, value2, "sysRolename");
            return (Criteria) this;
        }

        public Criteria andSysRoledescIsNull() {
            addCriterion("sys_roledesc is null");
            return (Criteria) this;
        }

        public Criteria andSysRoledescIsNotNull() {
            addCriterion("sys_roledesc is not null");
            return (Criteria) this;
        }

        public Criteria andSysRoledescEqualTo(String value) {
            addCriterion("sys_roledesc =", value, "sysRoledesc");
            return (Criteria) this;
        }

        public Criteria andSysRoledescNotEqualTo(String value) {
            addCriterion("sys_roledesc <>", value, "sysRoledesc");
            return (Criteria) this;
        }

        public Criteria andSysRoledescGreaterThan(String value) {
            addCriterion("sys_roledesc >", value, "sysRoledesc");
            return (Criteria) this;
        }

        public Criteria andSysRoledescGreaterThanOrEqualTo(String value) {
            addCriterion("sys_roledesc >=", value, "sysRoledesc");
            return (Criteria) this;
        }

        public Criteria andSysRoledescLessThan(String value) {
            addCriterion("sys_roledesc <", value, "sysRoledesc");
            return (Criteria) this;
        }

        public Criteria andSysRoledescLessThanOrEqualTo(String value) {
            addCriterion("sys_roledesc <=", value, "sysRoledesc");
            return (Criteria) this;
        }

        public Criteria andSysRoledescLike(String value) {
            addCriterion("sys_roledesc like", value, "sysRoledesc");
            return (Criteria) this;
        }

        public Criteria andSysRoledescNotLike(String value) {
            addCriterion("sys_roledesc not like", value, "sysRoledesc");
            return (Criteria) this;
        }

        public Criteria andSysRoledescIn(List<String> values) {
            addCriterion("sys_roledesc in", values, "sysRoledesc");
            return (Criteria) this;
        }

        public Criteria andSysRoledescNotIn(List<String> values) {
            addCriterion("sys_roledesc not in", values, "sysRoledesc");
            return (Criteria) this;
        }

        public Criteria andSysRoledescBetween(String value1, String value2) {
            addCriterion("sys_roledesc between", value1, value2, "sysRoledesc");
            return (Criteria) this;
        }

        public Criteria andSysRoledescNotBetween(String value1, String value2) {
            addCriterion("sys_roledesc not between", value1, value2, "sysRoledesc");
            return (Criteria) this;
        }

        public Criteria andEnableIsNull() {
            addCriterion("enable is null");
            return (Criteria) this;
        }

        public Criteria andEnableIsNotNull() {
            addCriterion("enable is not null");
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(Boolean value) {
            addCriterion("enable =", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotEqualTo(Boolean value) {
            addCriterion("enable <>", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThan(Boolean value) {
            addCriterion("enable >", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("enable >=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThan(Boolean value) {
            addCriterion("enable <", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThanOrEqualTo(Boolean value) {
            addCriterion("enable <=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableIn(List<Boolean> values) {
            addCriterion("enable in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotIn(List<Boolean> values) {
            addCriterion("enable not in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableBetween(Boolean value1, Boolean value2) {
            addCriterion("enable between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("enable not between", value1, value2, "enable");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_role
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}