package com.zkxh.demo.model.chat;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChatMsgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_msg
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_msg
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_msg
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated
     */
    public ChatMsgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chat_msg
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMsgIdIsNull() {
            addCriterion("msg_id is null");
            return (Criteria) this;
        }

        public Criteria andMsgIdIsNotNull() {
            addCriterion("msg_id is not null");
            return (Criteria) this;
        }

        public Criteria andMsgIdEqualTo(Integer value) {
            addCriterion("msg_id =", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotEqualTo(Integer value) {
            addCriterion("msg_id <>", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdGreaterThan(Integer value) {
            addCriterion("msg_id >", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("msg_id >=", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdLessThan(Integer value) {
            addCriterion("msg_id <", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdLessThanOrEqualTo(Integer value) {
            addCriterion("msg_id <=", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdIn(List<Integer> values) {
            addCriterion("msg_id in", values, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotIn(List<Integer> values) {
            addCriterion("msg_id not in", values, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdBetween(Integer value1, Integer value2) {
            addCriterion("msg_id between", value1, value2, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotBetween(Integer value1, Integer value2) {
            addCriterion("msg_id not between", value1, value2, "msgId");
            return (Criteria) this;
        }

        public Criteria andPostMsgIsNull() {
            addCriterion("post_msg is null");
            return (Criteria) this;
        }

        public Criteria andPostMsgIsNotNull() {
            addCriterion("post_msg is not null");
            return (Criteria) this;
        }

        public Criteria andPostMsgEqualTo(String value) {
            addCriterion("post_msg =", value, "postMsg");
            return (Criteria) this;
        }

        public Criteria andPostMsgNotEqualTo(String value) {
            addCriterion("post_msg <>", value, "postMsg");
            return (Criteria) this;
        }

        public Criteria andPostMsgGreaterThan(String value) {
            addCriterion("post_msg >", value, "postMsg");
            return (Criteria) this;
        }

        public Criteria andPostMsgGreaterThanOrEqualTo(String value) {
            addCriterion("post_msg >=", value, "postMsg");
            return (Criteria) this;
        }

        public Criteria andPostMsgLessThan(String value) {
            addCriterion("post_msg <", value, "postMsg");
            return (Criteria) this;
        }

        public Criteria andPostMsgLessThanOrEqualTo(String value) {
            addCriterion("post_msg <=", value, "postMsg");
            return (Criteria) this;
        }

        public Criteria andPostMsgLike(String value) {
            addCriterion("post_msg like", value, "postMsg");
            return (Criteria) this;
        }

        public Criteria andPostMsgNotLike(String value) {
            addCriterion("post_msg not like", value, "postMsg");
            return (Criteria) this;
        }

        public Criteria andPostMsgIn(List<String> values) {
            addCriterion("post_msg in", values, "postMsg");
            return (Criteria) this;
        }

        public Criteria andPostMsgNotIn(List<String> values) {
            addCriterion("post_msg not in", values, "postMsg");
            return (Criteria) this;
        }

        public Criteria andPostMsgBetween(String value1, String value2) {
            addCriterion("post_msg between", value1, value2, "postMsg");
            return (Criteria) this;
        }

        public Criteria andPostMsgNotBetween(String value1, String value2) {
            addCriterion("post_msg not between", value1, value2, "postMsg");
            return (Criteria) this;
        }

        public Criteria andLengthMsgIsNull() {
            addCriterion("length_msg is null");
            return (Criteria) this;
        }

        public Criteria andLengthMsgIsNotNull() {
            addCriterion("length_msg is not null");
            return (Criteria) this;
        }

        public Criteria andLengthMsgEqualTo(Integer value) {
            addCriterion("length_msg =", value, "lengthMsg");
            return (Criteria) this;
        }

        public Criteria andLengthMsgNotEqualTo(Integer value) {
            addCriterion("length_msg <>", value, "lengthMsg");
            return (Criteria) this;
        }

        public Criteria andLengthMsgGreaterThan(Integer value) {
            addCriterion("length_msg >", value, "lengthMsg");
            return (Criteria) this;
        }

        public Criteria andLengthMsgGreaterThanOrEqualTo(Integer value) {
            addCriterion("length_msg >=", value, "lengthMsg");
            return (Criteria) this;
        }

        public Criteria andLengthMsgLessThan(Integer value) {
            addCriterion("length_msg <", value, "lengthMsg");
            return (Criteria) this;
        }

        public Criteria andLengthMsgLessThanOrEqualTo(Integer value) {
            addCriterion("length_msg <=", value, "lengthMsg");
            return (Criteria) this;
        }

        public Criteria andLengthMsgIn(List<Integer> values) {
            addCriterion("length_msg in", values, "lengthMsg");
            return (Criteria) this;
        }

        public Criteria andLengthMsgNotIn(List<Integer> values) {
            addCriterion("length_msg not in", values, "lengthMsg");
            return (Criteria) this;
        }

        public Criteria andLengthMsgBetween(Integer value1, Integer value2) {
            addCriterion("length_msg between", value1, value2, "lengthMsg");
            return (Criteria) this;
        }

        public Criteria andLengthMsgNotBetween(Integer value1, Integer value2) {
            addCriterion("length_msg not between", value1, value2, "lengthMsg");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andPostTimeIsNull() {
            addCriterion("post_time is null");
            return (Criteria) this;
        }

        public Criteria andPostTimeIsNotNull() {
            addCriterion("post_time is not null");
            return (Criteria) this;
        }

        public Criteria andPostTimeEqualTo(Date value) {
            addCriterion("post_time =", value, "postTime");
            return (Criteria) this;
        }

        public Criteria andPostTimeNotEqualTo(Date value) {
            addCriterion("post_time <>", value, "postTime");
            return (Criteria) this;
        }

        public Criteria andPostTimeGreaterThan(Date value) {
            addCriterion("post_time >", value, "postTime");
            return (Criteria) this;
        }

        public Criteria andPostTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("post_time >=", value, "postTime");
            return (Criteria) this;
        }

        public Criteria andPostTimeLessThan(Date value) {
            addCriterion("post_time <", value, "postTime");
            return (Criteria) this;
        }

        public Criteria andPostTimeLessThanOrEqualTo(Date value) {
            addCriterion("post_time <=", value, "postTime");
            return (Criteria) this;
        }

        public Criteria andPostTimeIn(List<Date> values) {
            addCriterion("post_time in", values, "postTime");
            return (Criteria) this;
        }

        public Criteria andPostTimeNotIn(List<Date> values) {
            addCriterion("post_time not in", values, "postTime");
            return (Criteria) this;
        }

        public Criteria andPostTimeBetween(Date value1, Date value2) {
            addCriterion("post_time between", value1, value2, "postTime");
            return (Criteria) this;
        }

        public Criteria andPostTimeNotBetween(Date value1, Date value2) {
            addCriterion("post_time not between", value1, value2, "postTime");
            return (Criteria) this;
        }

        public Criteria andPostUserIdIsNull() {
            addCriterion("post_user_id is null");
            return (Criteria) this;
        }

        public Criteria andPostUserIdIsNotNull() {
            addCriterion("post_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andPostUserIdEqualTo(Integer value) {
            addCriterion("post_user_id =", value, "postUserId");
            return (Criteria) this;
        }

        public Criteria andPostUserIdNotEqualTo(Integer value) {
            addCriterion("post_user_id <>", value, "postUserId");
            return (Criteria) this;
        }

        public Criteria andPostUserIdGreaterThan(Integer value) {
            addCriterion("post_user_id >", value, "postUserId");
            return (Criteria) this;
        }

        public Criteria andPostUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("post_user_id >=", value, "postUserId");
            return (Criteria) this;
        }

        public Criteria andPostUserIdLessThan(Integer value) {
            addCriterion("post_user_id <", value, "postUserId");
            return (Criteria) this;
        }

        public Criteria andPostUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("post_user_id <=", value, "postUserId");
            return (Criteria) this;
        }

        public Criteria andPostUserIdIn(List<Integer> values) {
            addCriterion("post_user_id in", values, "postUserId");
            return (Criteria) this;
        }

        public Criteria andPostUserIdNotIn(List<Integer> values) {
            addCriterion("post_user_id not in", values, "postUserId");
            return (Criteria) this;
        }

        public Criteria andPostUserIdBetween(Integer value1, Integer value2) {
            addCriterion("post_user_id between", value1, value2, "postUserId");
            return (Criteria) this;
        }

        public Criteria andPostUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("post_user_id not between", value1, value2, "postUserId");
            return (Criteria) this;
        }

        public Criteria andPostIpIsNull() {
            addCriterion("post_ip is null");
            return (Criteria) this;
        }

        public Criteria andPostIpIsNotNull() {
            addCriterion("post_ip is not null");
            return (Criteria) this;
        }

        public Criteria andPostIpEqualTo(String value) {
            addCriterion("post_ip =", value, "postIp");
            return (Criteria) this;
        }

        public Criteria andPostIpNotEqualTo(String value) {
            addCriterion("post_ip <>", value, "postIp");
            return (Criteria) this;
        }

        public Criteria andPostIpGreaterThan(String value) {
            addCriterion("post_ip >", value, "postIp");
            return (Criteria) this;
        }

        public Criteria andPostIpGreaterThanOrEqualTo(String value) {
            addCriterion("post_ip >=", value, "postIp");
            return (Criteria) this;
        }

        public Criteria andPostIpLessThan(String value) {
            addCriterion("post_ip <", value, "postIp");
            return (Criteria) this;
        }

        public Criteria andPostIpLessThanOrEqualTo(String value) {
            addCriterion("post_ip <=", value, "postIp");
            return (Criteria) this;
        }

        public Criteria andPostIpLike(String value) {
            addCriterion("post_ip like", value, "postIp");
            return (Criteria) this;
        }

        public Criteria andPostIpNotLike(String value) {
            addCriterion("post_ip not like", value, "postIp");
            return (Criteria) this;
        }

        public Criteria andPostIpIn(List<String> values) {
            addCriterion("post_ip in", values, "postIp");
            return (Criteria) this;
        }

        public Criteria andPostIpNotIn(List<String> values) {
            addCriterion("post_ip not in", values, "postIp");
            return (Criteria) this;
        }

        public Criteria andPostIpBetween(String value1, String value2) {
            addCriterion("post_ip between", value1, value2, "postIp");
            return (Criteria) this;
        }

        public Criteria andPostIpNotBetween(String value1, String value2) {
            addCriterion("post_ip not between", value1, value2, "postIp");
            return (Criteria) this;
        }

        public Criteria andReceiveIpIsNull() {
            addCriterion("receive_ip is null");
            return (Criteria) this;
        }

        public Criteria andReceiveIpIsNotNull() {
            addCriterion("receive_ip is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveIpEqualTo(String value) {
            addCriterion("receive_ip =", value, "receiveIp");
            return (Criteria) this;
        }

        public Criteria andReceiveIpNotEqualTo(String value) {
            addCriterion("receive_ip <>", value, "receiveIp");
            return (Criteria) this;
        }

        public Criteria andReceiveIpGreaterThan(String value) {
            addCriterion("receive_ip >", value, "receiveIp");
            return (Criteria) this;
        }

        public Criteria andReceiveIpGreaterThanOrEqualTo(String value) {
            addCriterion("receive_ip >=", value, "receiveIp");
            return (Criteria) this;
        }

        public Criteria andReceiveIpLessThan(String value) {
            addCriterion("receive_ip <", value, "receiveIp");
            return (Criteria) this;
        }

        public Criteria andReceiveIpLessThanOrEqualTo(String value) {
            addCriterion("receive_ip <=", value, "receiveIp");
            return (Criteria) this;
        }

        public Criteria andReceiveIpLike(String value) {
            addCriterion("receive_ip like", value, "receiveIp");
            return (Criteria) this;
        }

        public Criteria andReceiveIpNotLike(String value) {
            addCriterion("receive_ip not like", value, "receiveIp");
            return (Criteria) this;
        }

        public Criteria andReceiveIpIn(List<String> values) {
            addCriterion("receive_ip in", values, "receiveIp");
            return (Criteria) this;
        }

        public Criteria andReceiveIpNotIn(List<String> values) {
            addCriterion("receive_ip not in", values, "receiveIp");
            return (Criteria) this;
        }

        public Criteria andReceiveIpBetween(String value1, String value2) {
            addCriterion("receive_ip between", value1, value2, "receiveIp");
            return (Criteria) this;
        }

        public Criteria andReceiveIpNotBetween(String value1, String value2) {
            addCriterion("receive_ip not between", value1, value2, "receiveIp");
            return (Criteria) this;
        }

        public Criteria andReceiceUserIdIsNull() {
            addCriterion("receice_user_id is null");
            return (Criteria) this;
        }

        public Criteria andReceiceUserIdIsNotNull() {
            addCriterion("receice_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andReceiceUserIdEqualTo(Integer value) {
            addCriterion("receice_user_id =", value, "receiceUserId");
            return (Criteria) this;
        }

        public Criteria andReceiceUserIdNotEqualTo(Integer value) {
            addCriterion("receice_user_id <>", value, "receiceUserId");
            return (Criteria) this;
        }

        public Criteria andReceiceUserIdGreaterThan(Integer value) {
            addCriterion("receice_user_id >", value, "receiceUserId");
            return (Criteria) this;
        }

        public Criteria andReceiceUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("receice_user_id >=", value, "receiceUserId");
            return (Criteria) this;
        }

        public Criteria andReceiceUserIdLessThan(Integer value) {
            addCriterion("receice_user_id <", value, "receiceUserId");
            return (Criteria) this;
        }

        public Criteria andReceiceUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("receice_user_id <=", value, "receiceUserId");
            return (Criteria) this;
        }

        public Criteria andReceiceUserIdIn(List<Integer> values) {
            addCriterion("receice_user_id in", values, "receiceUserId");
            return (Criteria) this;
        }

        public Criteria andReceiceUserIdNotIn(List<Integer> values) {
            addCriterion("receice_user_id not in", values, "receiceUserId");
            return (Criteria) this;
        }

        public Criteria andReceiceUserIdBetween(Integer value1, Integer value2) {
            addCriterion("receice_user_id between", value1, value2, "receiceUserId");
            return (Criteria) this;
        }

        public Criteria andReceiceUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("receice_user_id not between", value1, value2, "receiceUserId");
            return (Criteria) this;
        }

        public Criteria andTurnSendIsNull() {
            addCriterion("turn_send is null");
            return (Criteria) this;
        }

        public Criteria andTurnSendIsNotNull() {
            addCriterion("turn_send is not null");
            return (Criteria) this;
        }

        public Criteria andTurnSendEqualTo(Boolean value) {
            addCriterion("turn_send =", value, "turnSend");
            return (Criteria) this;
        }

        public Criteria andTurnSendNotEqualTo(Boolean value) {
            addCriterion("turn_send <>", value, "turnSend");
            return (Criteria) this;
        }

        public Criteria andTurnSendGreaterThan(Boolean value) {
            addCriterion("turn_send >", value, "turnSend");
            return (Criteria) this;
        }

        public Criteria andTurnSendGreaterThanOrEqualTo(Boolean value) {
            addCriterion("turn_send >=", value, "turnSend");
            return (Criteria) this;
        }

        public Criteria andTurnSendLessThan(Boolean value) {
            addCriterion("turn_send <", value, "turnSend");
            return (Criteria) this;
        }

        public Criteria andTurnSendLessThanOrEqualTo(Boolean value) {
            addCriterion("turn_send <=", value, "turnSend");
            return (Criteria) this;
        }

        public Criteria andTurnSendIn(List<Boolean> values) {
            addCriterion("turn_send in", values, "turnSend");
            return (Criteria) this;
        }

        public Criteria andTurnSendNotIn(List<Boolean> values) {
            addCriterion("turn_send not in", values, "turnSend");
            return (Criteria) this;
        }

        public Criteria andTurnSendBetween(Boolean value1, Boolean value2) {
            addCriterion("turn_send between", value1, value2, "turnSend");
            return (Criteria) this;
        }

        public Criteria andTurnSendNotBetween(Boolean value1, Boolean value2) {
            addCriterion("turn_send not between", value1, value2, "turnSend");
            return (Criteria) this;
        }

        public Criteria andStationIpIsNull() {
            addCriterion("station_ip is null");
            return (Criteria) this;
        }

        public Criteria andStationIpIsNotNull() {
            addCriterion("station_ip is not null");
            return (Criteria) this;
        }

        public Criteria andStationIpEqualTo(String value) {
            addCriterion("station_ip =", value, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpNotEqualTo(String value) {
            addCriterion("station_ip <>", value, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpGreaterThan(String value) {
            addCriterion("station_ip >", value, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpGreaterThanOrEqualTo(String value) {
            addCriterion("station_ip >=", value, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpLessThan(String value) {
            addCriterion("station_ip <", value, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpLessThanOrEqualTo(String value) {
            addCriterion("station_ip <=", value, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpLike(String value) {
            addCriterion("station_ip like", value, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpNotLike(String value) {
            addCriterion("station_ip not like", value, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpIn(List<String> values) {
            addCriterion("station_ip in", values, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpNotIn(List<String> values) {
            addCriterion("station_ip not in", values, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpBetween(String value1, String value2) {
            addCriterion("station_ip between", value1, value2, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpNotBetween(String value1, String value2) {
            addCriterion("station_ip not between", value1, value2, "stationIp");
            return (Criteria) this;
        }

        public Criteria andConvertTimeIsNull() {
            addCriterion("convert_time is null");
            return (Criteria) this;
        }

        public Criteria andConvertTimeIsNotNull() {
            addCriterion("convert_time is not null");
            return (Criteria) this;
        }

        public Criteria andConvertTimeEqualTo(Date value) {
            addCriterion("convert_time =", value, "convertTime");
            return (Criteria) this;
        }

        public Criteria andConvertTimeNotEqualTo(Date value) {
            addCriterion("convert_time <>", value, "convertTime");
            return (Criteria) this;
        }

        public Criteria andConvertTimeGreaterThan(Date value) {
            addCriterion("convert_time >", value, "convertTime");
            return (Criteria) this;
        }

        public Criteria andConvertTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("convert_time >=", value, "convertTime");
            return (Criteria) this;
        }

        public Criteria andConvertTimeLessThan(Date value) {
            addCriterion("convert_time <", value, "convertTime");
            return (Criteria) this;
        }

        public Criteria andConvertTimeLessThanOrEqualTo(Date value) {
            addCriterion("convert_time <=", value, "convertTime");
            return (Criteria) this;
        }

        public Criteria andConvertTimeIn(List<Date> values) {
            addCriterion("convert_time in", values, "convertTime");
            return (Criteria) this;
        }

        public Criteria andConvertTimeNotIn(List<Date> values) {
            addCriterion("convert_time not in", values, "convertTime");
            return (Criteria) this;
        }

        public Criteria andConvertTimeBetween(Date value1, Date value2) {
            addCriterion("convert_time between", value1, value2, "convertTime");
            return (Criteria) this;
        }

        public Criteria andConvertTimeNotBetween(Date value1, Date value2) {
            addCriterion("convert_time not between", value1, value2, "convertTime");
            return (Criteria) this;
        }

        public Criteria andTerminalIdIsNull() {
            addCriterion("terminal_id is null");
            return (Criteria) this;
        }

        public Criteria andTerminalIdIsNotNull() {
            addCriterion("terminal_id is not null");
            return (Criteria) this;
        }

        public Criteria andTerminalIdEqualTo(Integer value) {
            addCriterion("terminal_id =", value, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdNotEqualTo(Integer value) {
            addCriterion("terminal_id <>", value, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdGreaterThan(Integer value) {
            addCriterion("terminal_id >", value, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("terminal_id >=", value, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdLessThan(Integer value) {
            addCriterion("terminal_id <", value, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdLessThanOrEqualTo(Integer value) {
            addCriterion("terminal_id <=", value, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdIn(List<Integer> values) {
            addCriterion("terminal_id in", values, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdNotIn(List<Integer> values) {
            addCriterion("terminal_id not in", values, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdBetween(Integer value1, Integer value2) {
            addCriterion("terminal_id between", value1, value2, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdNotBetween(Integer value1, Integer value2) {
            addCriterion("terminal_id not between", value1, value2, "terminalId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chat_msg
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chat_msg
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}