package com.zkxh.demo.model.chat;

import com.zkxh.demo.common.base.entity.BaseEntity;

import java.util.Date;

public class ChatMsg extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.msg_id
     *
     * @mbg.generated
     */
    private Integer msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.post_msg
     *
     * @mbg.generated
     */
    private String postMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.length_msg
     *
     * @mbg.generated
     */
    private Integer lengthMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.post_time
     *
     * @mbg.generated
     */
    private Date postTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.post_user_id
     *
     * @mbg.generated
     */
    private Integer postUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.post_ip
     *
     * @mbg.generated
     */
    private String postIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.receive_ip
     *
     * @mbg.generated
     */
    private String receiveIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.receice_user_id
     *
     * @mbg.generated
     */
    private Integer receiceUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.turn_send
     *
     * @mbg.generated
     */
    private Boolean turnSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.station_ip
     *
     * @mbg.generated
     */
    private String stationIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.convert_time
     *
     * @mbg.generated
     */
    private Date convertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.terminal_id
     *
     * @mbg.generated
     */
    private Integer terminalId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.msg_id
     *
     * @return the value of chat_msg.msg_id
     * @mbg.generated
     */
    public Integer getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.msg_id
     *
     * @param msgId the value for chat_msg.msg_id
     * @mbg.generated
     */
    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.post_msg
     *
     * @return the value of chat_msg.post_msg
     * @mbg.generated
     */
    public String getPostMsg() {
        return postMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.post_msg
     *
     * @param postMsg the value for chat_msg.post_msg
     * @mbg.generated
     */
    public void setPostMsg(String postMsg) {
        this.postMsg = postMsg == null ? null : postMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.length_msg
     *
     * @return the value of chat_msg.length_msg
     * @mbg.generated
     */
    public Integer getLengthMsg() {
        return lengthMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.length_msg
     *
     * @param lengthMsg the value for chat_msg.length_msg
     * @mbg.generated
     */
    public void setLengthMsg(Integer lengthMsg) {
        this.lengthMsg = lengthMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.status
     *
     * @return the value of chat_msg.status
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.status
     *
     * @param status the value for chat_msg.status
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.post_time
     *
     * @return the value of chat_msg.post_time
     * @mbg.generated
     */
    public Date getPostTime() {
        return postTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.post_time
     *
     * @param postTime the value for chat_msg.post_time
     * @mbg.generated
     */
    public void setPostTime(Date postTime) {
        this.postTime = postTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.post_user_id
     *
     * @return the value of chat_msg.post_user_id
     * @mbg.generated
     */
    public Integer getPostUserId() {
        return postUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.post_user_id
     *
     * @param postUserId the value for chat_msg.post_user_id
     * @mbg.generated
     */
    public void setPostUserId(Integer postUserId) {
        this.postUserId = postUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.post_ip
     *
     * @return the value of chat_msg.post_ip
     * @mbg.generated
     */
    public String getPostIp() {
        return postIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.post_ip
     *
     * @param postIp the value for chat_msg.post_ip
     * @mbg.generated
     */
    public void setPostIp(String postIp) {
        this.postIp = postIp == null ? null : postIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.receive_ip
     *
     * @return the value of chat_msg.receive_ip
     * @mbg.generated
     */
    public String getReceiveIp() {
        return receiveIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.receive_ip
     *
     * @param receiveIp the value for chat_msg.receive_ip
     * @mbg.generated
     */
    public void setReceiveIp(String receiveIp) {
        this.receiveIp = receiveIp == null ? null : receiveIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.receice_user_id
     *
     * @return the value of chat_msg.receice_user_id
     * @mbg.generated
     */
    public Integer getReceiceUserId() {
        return receiceUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.receice_user_id
     *
     * @param receiceUserId the value for chat_msg.receice_user_id
     * @mbg.generated
     */
    public void setReceiceUserId(Integer receiceUserId) {
        this.receiceUserId = receiceUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.turn_send
     *
     * @return the value of chat_msg.turn_send
     * @mbg.generated
     */
    public Boolean getTurnSend() {
        return turnSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.turn_send
     *
     * @param turnSend the value for chat_msg.turn_send
     * @mbg.generated
     */
    public void setTurnSend(Boolean turnSend) {
        this.turnSend = turnSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.station_ip
     *
     * @return the value of chat_msg.station_ip
     * @mbg.generated
     */
    public String getStationIp() {
        return stationIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.station_ip
     *
     * @param stationIp the value for chat_msg.station_ip
     * @mbg.generated
     */
    public void setStationIp(String stationIp) {
        this.stationIp = stationIp == null ? null : stationIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.convert_time
     *
     * @return the value of chat_msg.convert_time
     * @mbg.generated
     */
    public Date getConvertTime() {
        return convertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.convert_time
     *
     * @param convertTime the value for chat_msg.convert_time
     * @mbg.generated
     */
    public void setConvertTime(Date convertTime) {
        this.convertTime = convertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.terminal_id
     *
     * @return the value of chat_msg.terminal_id
     * @mbg.generated
     */
    public Integer getTerminalId() {
        return terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.terminal_id
     *
     * @param terminalId the value for chat_msg.terminal_id
     * @mbg.generated
     */
    public void setTerminalId(Integer terminalId) {
        this.terminalId = terminalId;
    }
}
