spring:
  kafka:
    # 指定kafka 代理地址，可以多个
    bootstrap-servers: 192.168.205.128:9092,192.168.205.129:9092,192.168.205.130:9092
    producer:
      retries: 0
      # 每次批量发送消息的数量
      batch-size: 16384
      # 缓存容量
      buffer-memory: 33554432
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      # 指定默认消费者group id
      group-id: consumer-tutorial
      auto-commit-interval: 100
      auto-offset-reset: earliest
      enable-auto-commit: true
      # 指定消息key和消息体的编解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    # 指定listener 容器中的线程数，用于提高并发量
    listener:
      concurrency: 3

  #配置redis数据库
  redis:
    database: 0
    host: 192.168.205.128
    port: 6379
    #    password: root
    timeout: 5000
    jedis:
      pool:
        max-active: 2000
        max-idle: 500
        max-wait: 5000
        min-idle: 200
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zkxh123
    url: jdbc:mysql://127.0.0.1:3306/zkxh?useUnicode=true&characterEncoding=utf-8&useSSL=false
    druid:
      #      first:  #数据源1
      #        url: jdbc:mysql://127.0.0.1:3306/detection?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      #        username: root
      #        password: zkxh123
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
  #mvc设置
  mvc:
    favicon:
      enabled: false
  #热部署配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  resources:
    static-locations: classpath:resources/**
#打印日志
logging:
  level:
    org.crazycake.shiro.RedisSessionDAO: DEBUG
    #    org.springframework.web: DEBUG
    com.zkxh.demo.dao: DEBUG
  config: classpath:logback-boot.xml
#端口号配置
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /
  port: 8888
#mybatis-plus 配置
#mybatis-plus:
#  config-location: classpath:resources/mapping/**/*.xml
mybatis:
  #type-aliases-package: com.zkxh.demo.model.*.*
  mapper-locations: com\\zkxh\\demo\\dao\\*.xml
# shiro 数据源配置 数据库 01

redis:
  shiro:
    host: 192.168.205.128
    port: 6379
    #  password:
    database: 1
    timeout: 5000