package com.zkxh.demo.dao.sys_menu_role;

import com.zkxh.demo.model.sys_menu_role.SysMenuRole;
import com.zkxh.demo.model.sys_menu_role.SysMenuRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysMenuRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbg.generated
     */
    long countByExample(SysMenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbg.generated
     */
    int deleteByExample(SysMenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer menuRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbg.generated
     */
    int insert(SysMenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbg.generated
     */
    int insertSelective(SysMenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbg.generated
     */
    List<SysMenuRole> selectByExample(SysMenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbg.generated
     */
    SysMenuRole selectByPrimaryKey(Integer menuRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysMenuRole record, @Param("example") SysMenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysMenuRole record, @Param("example") SysMenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysMenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysMenuRole record);


    List<SysMenuRole> selectSysMenuRoleByRoleIdOfPermission(Integer roleId);

    List<SysMenuRole> selectSysMenuRoleByRoleIdOfMenus(Integer roleId);
}