package com.zkxh.demo.model.zone;

public class Zone {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.zone_id
     *
     * @mbg.generated
     */
    private Integer zoneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.zone_name
     *
     * @mbg.generated
     */
    private String zoneName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.zone_parent_id
     *
     * @mbg.generated
     */
    private Integer zoneParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.zone_type
     *
     * @mbg.generated
     */
    private Integer zoneType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.zone_id
     *
     * @return the value of zone.zone_id
     *
     * @mbg.generated
     */
    public Integer getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.zone_id
     *
     * @param zoneId the value for zone.zone_id
     *
     * @mbg.generated
     */
    public void setZoneId(Integer zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.zone_name
     *
     * @return the value of zone.zone_name
     *
     * @mbg.generated
     */
    public String getZoneName() {
        return zoneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.zone_name
     *
     * @param zoneName the value for zone.zone_name
     *
     * @mbg.generated
     */
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName == null ? null : zoneName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.zone_parent_id
     *
     * @return the value of zone.zone_parent_id
     *
     * @mbg.generated
     */
    public Integer getZoneParentId() {
        return zoneParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.zone_parent_id
     *
     * @param zoneParentId the value for zone.zone_parent_id
     *
     * @mbg.generated
     */
    public void setZoneParentId(Integer zoneParentId) {
        this.zoneParentId = zoneParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.zone_type
     *
     * @return the value of zone.zone_type
     *
     * @mbg.generated
     */
    public Integer getZoneType() {
        return zoneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.zone_type
     *
     * @param zoneType the value for zone.zone_type
     *
     * @mbg.generated
     */
    public void setZoneType(Integer zoneType) {
        this.zoneType = zoneType;
    }
}