package com.zkxh.demo.model.staff;

import com.zkxh.demo.common.base.entity.BaseEntity;

import java.util.Date;

public class StaffTerminal extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.staff_terminal_id
     *
     * @mbg.generated
     */
    private Integer staffTerminalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.staff_id
     *
     * @mbg.generated
     */
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.terminal_id
     *
     * @mbg.generated
     */
    private Integer terminalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.is_person
     *
     * @mbg.generated
     */
    private Boolean isPerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.staff_terminal_id
     *
     * @return the value of staff_terminal.staff_terminal_id
     * @mbg.generated
     */
    public Integer getStaffTerminalId() {
        return staffTerminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.staff_terminal_id
     *
     * @param staffTerminalId the value for staff_terminal.staff_terminal_id
     * @mbg.generated
     */
    public void setStaffTerminalId(Integer staffTerminalId) {
        this.staffTerminalId = staffTerminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.staff_id
     *
     * @return the value of staff_terminal.staff_id
     * @mbg.generated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.staff_id
     *
     * @param staffId the value for staff_terminal.staff_id
     * @mbg.generated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.terminal_id
     *
     * @return the value of staff_terminal.terminal_id
     * @mbg.generated
     */
    public Integer getTerminalId() {
        return terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.terminal_id
     *
     * @param terminalId the value for staff_terminal.terminal_id
     * @mbg.generated
     */
    public void setTerminalId(Integer terminalId) {
        this.terminalId = terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.create_time
     *
     * @return the value of staff_terminal.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.create_time
     *
     * @param createTime the value for staff_terminal.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.is_person
     *
     * @return the value of staff_terminal.is_person
     * @mbg.generated
     */
    public Boolean getIsPerson() {
        return isPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.is_person
     *
     * @param isPerson the value for staff_terminal.is_person
     * @mbg.generated
     */
    public void setIsPerson(Boolean isPerson) {
        this.isPerson = isPerson;
    }
}