package com.zkxh.demo.model.staff;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class StaffExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated
     */
    public StaffExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table staff
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andStaffIdIsNull() {
            addCriterion("staff_id is null");
            return (Criteria) this;
        }

        public Criteria andStaffIdIsNotNull() {
            addCriterion("staff_id is not null");
            return (Criteria) this;
        }

        public Criteria andStaffIdEqualTo(Integer value) {
            addCriterion("staff_id =", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotEqualTo(Integer value) {
            addCriterion("staff_id <>", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThan(Integer value) {
            addCriterion("staff_id >", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("staff_id >=", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThan(Integer value) {
            addCriterion("staff_id <", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThanOrEqualTo(Integer value) {
            addCriterion("staff_id <=", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdIn(List<Integer> values) {
            addCriterion("staff_id in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotIn(List<Integer> values) {
            addCriterion("staff_id not in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdBetween(Integer value1, Integer value2) {
            addCriterion("staff_id between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotBetween(Integer value1, Integer value2) {
            addCriterion("staff_id not between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffNumberIsNull() {
            addCriterion("staff_number is null");
            return (Criteria) this;
        }

        public Criteria andStaffNumberIsNotNull() {
            addCriterion("staff_number is not null");
            return (Criteria) this;
        }

        public Criteria andStaffNumberEqualTo(String value) {
            addCriterion("staff_number =", value, "staffNumber");
            return (Criteria) this;
        }

        public Criteria andStaffNumberNotEqualTo(String value) {
            addCriterion("staff_number <>", value, "staffNumber");
            return (Criteria) this;
        }

        public Criteria andStaffNumberGreaterThan(String value) {
            addCriterion("staff_number >", value, "staffNumber");
            return (Criteria) this;
        }

        public Criteria andStaffNumberGreaterThanOrEqualTo(String value) {
            addCriterion("staff_number >=", value, "staffNumber");
            return (Criteria) this;
        }

        public Criteria andStaffNumberLessThan(String value) {
            addCriterion("staff_number <", value, "staffNumber");
            return (Criteria) this;
        }

        public Criteria andStaffNumberLessThanOrEqualTo(String value) {
            addCriterion("staff_number <=", value, "staffNumber");
            return (Criteria) this;
        }

        public Criteria andStaffNumberLike(String value) {
            addCriterion("staff_number like", value, "staffNumber");
            return (Criteria) this;
        }

        public Criteria andStaffNumberNotLike(String value) {
            addCriterion("staff_number not like", value, "staffNumber");
            return (Criteria) this;
        }

        public Criteria andStaffNumberIn(List<String> values) {
            addCriterion("staff_number in", values, "staffNumber");
            return (Criteria) this;
        }

        public Criteria andStaffNumberNotIn(List<String> values) {
            addCriterion("staff_number not in", values, "staffNumber");
            return (Criteria) this;
        }

        public Criteria andStaffNumberBetween(String value1, String value2) {
            addCriterion("staff_number between", value1, value2, "staffNumber");
            return (Criteria) this;
        }

        public Criteria andStaffNumberNotBetween(String value1, String value2) {
            addCriterion("staff_number not between", value1, value2, "staffNumber");
            return (Criteria) this;
        }

        public Criteria andStaffNameIsNull() {
            addCriterion("staff_name is null");
            return (Criteria) this;
        }

        public Criteria andStaffNameIsNotNull() {
            addCriterion("staff_name is not null");
            return (Criteria) this;
        }

        public Criteria andStaffNameEqualTo(String value) {
            addCriterion("staff_name =", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotEqualTo(String value) {
            addCriterion("staff_name <>", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameGreaterThan(String value) {
            addCriterion("staff_name >", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameGreaterThanOrEqualTo(String value) {
            addCriterion("staff_name >=", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLessThan(String value) {
            addCriterion("staff_name <", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLessThanOrEqualTo(String value) {
            addCriterion("staff_name <=", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLike(String value) {
            addCriterion("staff_name like", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotLike(String value) {
            addCriterion("staff_name not like", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameIn(List<String> values) {
            addCriterion("staff_name in", values, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotIn(List<String> values) {
            addCriterion("staff_name not in", values, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameBetween(String value1, String value2) {
            addCriterion("staff_name between", value1, value2, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotBetween(String value1, String value2) {
            addCriterion("staff_name not between", value1, value2, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffSexIsNull() {
            addCriterion("staff_sex is null");
            return (Criteria) this;
        }

        public Criteria andStaffSexIsNotNull() {
            addCriterion("staff_sex is not null");
            return (Criteria) this;
        }

        public Criteria andStaffSexEqualTo(Boolean value) {
            addCriterion("staff_sex =", value, "staffSex");
            return (Criteria) this;
        }

        public Criteria andStaffSexNotEqualTo(Boolean value) {
            addCriterion("staff_sex <>", value, "staffSex");
            return (Criteria) this;
        }

        public Criteria andStaffSexGreaterThan(Boolean value) {
            addCriterion("staff_sex >", value, "staffSex");
            return (Criteria) this;
        }

        public Criteria andStaffSexGreaterThanOrEqualTo(Boolean value) {
            addCriterion("staff_sex >=", value, "staffSex");
            return (Criteria) this;
        }

        public Criteria andStaffSexLessThan(Boolean value) {
            addCriterion("staff_sex <", value, "staffSex");
            return (Criteria) this;
        }

        public Criteria andStaffSexLessThanOrEqualTo(Boolean value) {
            addCriterion("staff_sex <=", value, "staffSex");
            return (Criteria) this;
        }

        public Criteria andStaffSexIn(List<Boolean> values) {
            addCriterion("staff_sex in", values, "staffSex");
            return (Criteria) this;
        }

        public Criteria andStaffSexNotIn(List<Boolean> values) {
            addCriterion("staff_sex not in", values, "staffSex");
            return (Criteria) this;
        }

        public Criteria andStaffSexBetween(Boolean value1, Boolean value2) {
            addCriterion("staff_sex between", value1, value2, "staffSex");
            return (Criteria) this;
        }

        public Criteria andStaffSexNotBetween(Boolean value1, Boolean value2) {
            addCriterion("staff_sex not between", value1, value2, "staffSex");
            return (Criteria) this;
        }

        public Criteria andStaffBirthdayIsNull() {
            addCriterion("staff_birthday is null");
            return (Criteria) this;
        }

        public Criteria andStaffBirthdayIsNotNull() {
            addCriterion("staff_birthday is not null");
            return (Criteria) this;
        }

        public Criteria andStaffBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("staff_birthday =", value, "staffBirthday");
            return (Criteria) this;
        }

        public Criteria andStaffBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("staff_birthday <>", value, "staffBirthday");
            return (Criteria) this;
        }

        public Criteria andStaffBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("staff_birthday >", value, "staffBirthday");
            return (Criteria) this;
        }

        public Criteria andStaffBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("staff_birthday >=", value, "staffBirthday");
            return (Criteria) this;
        }

        public Criteria andStaffBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("staff_birthday <", value, "staffBirthday");
            return (Criteria) this;
        }

        public Criteria andStaffBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("staff_birthday <=", value, "staffBirthday");
            return (Criteria) this;
        }

        public Criteria andStaffBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("staff_birthday in", values, "staffBirthday");
            return (Criteria) this;
        }

        public Criteria andStaffBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("staff_birthday not in", values, "staffBirthday");
            return (Criteria) this;
        }

        public Criteria andStaffBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("staff_birthday between", value1, value2, "staffBirthday");
            return (Criteria) this;
        }

        public Criteria andStaffBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("staff_birthday not between", value1, value2, "staffBirthday");
            return (Criteria) this;
        }

        public Criteria andStaffIdCardIsNull() {
            addCriterion("staff_id_card is null");
            return (Criteria) this;
        }

        public Criteria andStaffIdCardIsNotNull() {
            addCriterion("staff_id_card is not null");
            return (Criteria) this;
        }

        public Criteria andStaffIdCardEqualTo(String value) {
            addCriterion("staff_id_card =", value, "staffIdCard");
            return (Criteria) this;
        }

        public Criteria andStaffIdCardNotEqualTo(String value) {
            addCriterion("staff_id_card <>", value, "staffIdCard");
            return (Criteria) this;
        }

        public Criteria andStaffIdCardGreaterThan(String value) {
            addCriterion("staff_id_card >", value, "staffIdCard");
            return (Criteria) this;
        }

        public Criteria andStaffIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("staff_id_card >=", value, "staffIdCard");
            return (Criteria) this;
        }

        public Criteria andStaffIdCardLessThan(String value) {
            addCriterion("staff_id_card <", value, "staffIdCard");
            return (Criteria) this;
        }

        public Criteria andStaffIdCardLessThanOrEqualTo(String value) {
            addCriterion("staff_id_card <=", value, "staffIdCard");
            return (Criteria) this;
        }

        public Criteria andStaffIdCardLike(String value) {
            addCriterion("staff_id_card like", value, "staffIdCard");
            return (Criteria) this;
        }

        public Criteria andStaffIdCardNotLike(String value) {
            addCriterion("staff_id_card not like", value, "staffIdCard");
            return (Criteria) this;
        }

        public Criteria andStaffIdCardIn(List<String> values) {
            addCriterion("staff_id_card in", values, "staffIdCard");
            return (Criteria) this;
        }

        public Criteria andStaffIdCardNotIn(List<String> values) {
            addCriterion("staff_id_card not in", values, "staffIdCard");
            return (Criteria) this;
        }

        public Criteria andStaffIdCardBetween(String value1, String value2) {
            addCriterion("staff_id_card between", value1, value2, "staffIdCard");
            return (Criteria) this;
        }

        public Criteria andStaffIdCardNotBetween(String value1, String value2) {
            addCriterion("staff_id_card not between", value1, value2, "staffIdCard");
            return (Criteria) this;
        }

        public Criteria andStaffWedlockIsNull() {
            addCriterion("staff_wedlock is null");
            return (Criteria) this;
        }

        public Criteria andStaffWedlockIsNotNull() {
            addCriterion("staff_wedlock is not null");
            return (Criteria) this;
        }

        public Criteria andStaffWedlockEqualTo(String value) {
            addCriterion("staff_wedlock =", value, "staffWedlock");
            return (Criteria) this;
        }

        public Criteria andStaffWedlockNotEqualTo(String value) {
            addCriterion("staff_wedlock <>", value, "staffWedlock");
            return (Criteria) this;
        }

        public Criteria andStaffWedlockGreaterThan(String value) {
            addCriterion("staff_wedlock >", value, "staffWedlock");
            return (Criteria) this;
        }

        public Criteria andStaffWedlockGreaterThanOrEqualTo(String value) {
            addCriterion("staff_wedlock >=", value, "staffWedlock");
            return (Criteria) this;
        }

        public Criteria andStaffWedlockLessThan(String value) {
            addCriterion("staff_wedlock <", value, "staffWedlock");
            return (Criteria) this;
        }

        public Criteria andStaffWedlockLessThanOrEqualTo(String value) {
            addCriterion("staff_wedlock <=", value, "staffWedlock");
            return (Criteria) this;
        }

        public Criteria andStaffWedlockLike(String value) {
            addCriterion("staff_wedlock like", value, "staffWedlock");
            return (Criteria) this;
        }

        public Criteria andStaffWedlockNotLike(String value) {
            addCriterion("staff_wedlock not like", value, "staffWedlock");
            return (Criteria) this;
        }

        public Criteria andStaffWedlockIn(List<String> values) {
            addCriterion("staff_wedlock in", values, "staffWedlock");
            return (Criteria) this;
        }

        public Criteria andStaffWedlockNotIn(List<String> values) {
            addCriterion("staff_wedlock not in", values, "staffWedlock");
            return (Criteria) this;
        }

        public Criteria andStaffWedlockBetween(String value1, String value2) {
            addCriterion("staff_wedlock between", value1, value2, "staffWedlock");
            return (Criteria) this;
        }

        public Criteria andStaffWedlockNotBetween(String value1, String value2) {
            addCriterion("staff_wedlock not between", value1, value2, "staffWedlock");
            return (Criteria) this;
        }

        public Criteria andStaffEmailIsNull() {
            addCriterion("staff_email is null");
            return (Criteria) this;
        }

        public Criteria andStaffEmailIsNotNull() {
            addCriterion("staff_email is not null");
            return (Criteria) this;
        }

        public Criteria andStaffEmailEqualTo(String value) {
            addCriterion("staff_email =", value, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailNotEqualTo(String value) {
            addCriterion("staff_email <>", value, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailGreaterThan(String value) {
            addCriterion("staff_email >", value, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailGreaterThanOrEqualTo(String value) {
            addCriterion("staff_email >=", value, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailLessThan(String value) {
            addCriterion("staff_email <", value, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailLessThanOrEqualTo(String value) {
            addCriterion("staff_email <=", value, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailLike(String value) {
            addCriterion("staff_email like", value, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailNotLike(String value) {
            addCriterion("staff_email not like", value, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailIn(List<String> values) {
            addCriterion("staff_email in", values, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailNotIn(List<String> values) {
            addCriterion("staff_email not in", values, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailBetween(String value1, String value2) {
            addCriterion("staff_email between", value1, value2, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailNotBetween(String value1, String value2) {
            addCriterion("staff_email not between", value1, value2, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffAddressIsNull() {
            addCriterion("staff_address is null");
            return (Criteria) this;
        }

        public Criteria andStaffAddressIsNotNull() {
            addCriterion("staff_address is not null");
            return (Criteria) this;
        }

        public Criteria andStaffAddressEqualTo(String value) {
            addCriterion("staff_address =", value, "staffAddress");
            return (Criteria) this;
        }

        public Criteria andStaffAddressNotEqualTo(String value) {
            addCriterion("staff_address <>", value, "staffAddress");
            return (Criteria) this;
        }

        public Criteria andStaffAddressGreaterThan(String value) {
            addCriterion("staff_address >", value, "staffAddress");
            return (Criteria) this;
        }

        public Criteria andStaffAddressGreaterThanOrEqualTo(String value) {
            addCriterion("staff_address >=", value, "staffAddress");
            return (Criteria) this;
        }

        public Criteria andStaffAddressLessThan(String value) {
            addCriterion("staff_address <", value, "staffAddress");
            return (Criteria) this;
        }

        public Criteria andStaffAddressLessThanOrEqualTo(String value) {
            addCriterion("staff_address <=", value, "staffAddress");
            return (Criteria) this;
        }

        public Criteria andStaffAddressLike(String value) {
            addCriterion("staff_address like", value, "staffAddress");
            return (Criteria) this;
        }

        public Criteria andStaffAddressNotLike(String value) {
            addCriterion("staff_address not like", value, "staffAddress");
            return (Criteria) this;
        }

        public Criteria andStaffAddressIn(List<String> values) {
            addCriterion("staff_address in", values, "staffAddress");
            return (Criteria) this;
        }

        public Criteria andStaffAddressNotIn(List<String> values) {
            addCriterion("staff_address not in", values, "staffAddress");
            return (Criteria) this;
        }

        public Criteria andStaffAddressBetween(String value1, String value2) {
            addCriterion("staff_address between", value1, value2, "staffAddress");
            return (Criteria) this;
        }

        public Criteria andStaffAddressNotBetween(String value1, String value2) {
            addCriterion("staff_address not between", value1, value2, "staffAddress");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneIsNull() {
            addCriterion("staff_phone is null");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneIsNotNull() {
            addCriterion("staff_phone is not null");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneEqualTo(String value) {
            addCriterion("staff_phone =", value, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneNotEqualTo(String value) {
            addCriterion("staff_phone <>", value, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneGreaterThan(String value) {
            addCriterion("staff_phone >", value, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("staff_phone >=", value, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneLessThan(String value) {
            addCriterion("staff_phone <", value, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneLessThanOrEqualTo(String value) {
            addCriterion("staff_phone <=", value, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneLike(String value) {
            addCriterion("staff_phone like", value, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneNotLike(String value) {
            addCriterion("staff_phone not like", value, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneIn(List<String> values) {
            addCriterion("staff_phone in", values, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneNotIn(List<String> values) {
            addCriterion("staff_phone not in", values, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneBetween(String value1, String value2) {
            addCriterion("staff_phone between", value1, value2, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneNotBetween(String value1, String value2) {
            addCriterion("staff_phone not between", value1, value2, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffJobIdIsNull() {
            addCriterion("staff_job_id is null");
            return (Criteria) this;
        }

        public Criteria andStaffJobIdIsNotNull() {
            addCriterion("staff_job_id is not null");
            return (Criteria) this;
        }

        public Criteria andStaffJobIdEqualTo(Integer value) {
            addCriterion("staff_job_id =", value, "staffJobId");
            return (Criteria) this;
        }

        public Criteria andStaffJobIdNotEqualTo(Integer value) {
            addCriterion("staff_job_id <>", value, "staffJobId");
            return (Criteria) this;
        }

        public Criteria andStaffJobIdGreaterThan(Integer value) {
            addCriterion("staff_job_id >", value, "staffJobId");
            return (Criteria) this;
        }

        public Criteria andStaffJobIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("staff_job_id >=", value, "staffJobId");
            return (Criteria) this;
        }

        public Criteria andStaffJobIdLessThan(Integer value) {
            addCriterion("staff_job_id <", value, "staffJobId");
            return (Criteria) this;
        }

        public Criteria andStaffJobIdLessThanOrEqualTo(Integer value) {
            addCriterion("staff_job_id <=", value, "staffJobId");
            return (Criteria) this;
        }

        public Criteria andStaffJobIdIn(List<Integer> values) {
            addCriterion("staff_job_id in", values, "staffJobId");
            return (Criteria) this;
        }

        public Criteria andStaffJobIdNotIn(List<Integer> values) {
            addCriterion("staff_job_id not in", values, "staffJobId");
            return (Criteria) this;
        }

        public Criteria andStaffJobIdBetween(Integer value1, Integer value2) {
            addCriterion("staff_job_id between", value1, value2, "staffJobId");
            return (Criteria) this;
        }

        public Criteria andStaffJobIdNotBetween(Integer value1, Integer value2) {
            addCriterion("staff_job_id not between", value1, value2, "staffJobId");
            return (Criteria) this;
        }

        public Criteria andStaffNativePlaceIsNull() {
            addCriterion("staff_native_place is null");
            return (Criteria) this;
        }

        public Criteria andStaffNativePlaceIsNotNull() {
            addCriterion("staff_native_place is not null");
            return (Criteria) this;
        }

        public Criteria andStaffNativePlaceEqualTo(String value) {
            addCriterion("staff_native_place =", value, "staffNativePlace");
            return (Criteria) this;
        }

        public Criteria andStaffNativePlaceNotEqualTo(String value) {
            addCriterion("staff_native_place <>", value, "staffNativePlace");
            return (Criteria) this;
        }

        public Criteria andStaffNativePlaceGreaterThan(String value) {
            addCriterion("staff_native_place >", value, "staffNativePlace");
            return (Criteria) this;
        }

        public Criteria andStaffNativePlaceGreaterThanOrEqualTo(String value) {
            addCriterion("staff_native_place >=", value, "staffNativePlace");
            return (Criteria) this;
        }

        public Criteria andStaffNativePlaceLessThan(String value) {
            addCriterion("staff_native_place <", value, "staffNativePlace");
            return (Criteria) this;
        }

        public Criteria andStaffNativePlaceLessThanOrEqualTo(String value) {
            addCriterion("staff_native_place <=", value, "staffNativePlace");
            return (Criteria) this;
        }

        public Criteria andStaffNativePlaceLike(String value) {
            addCriterion("staff_native_place like", value, "staffNativePlace");
            return (Criteria) this;
        }

        public Criteria andStaffNativePlaceNotLike(String value) {
            addCriterion("staff_native_place not like", value, "staffNativePlace");
            return (Criteria) this;
        }

        public Criteria andStaffNativePlaceIn(List<String> values) {
            addCriterion("staff_native_place in", values, "staffNativePlace");
            return (Criteria) this;
        }

        public Criteria andStaffNativePlaceNotIn(List<String> values) {
            addCriterion("staff_native_place not in", values, "staffNativePlace");
            return (Criteria) this;
        }

        public Criteria andStaffNativePlaceBetween(String value1, String value2) {
            addCriterion("staff_native_place between", value1, value2, "staffNativePlace");
            return (Criteria) this;
        }

        public Criteria andStaffNativePlaceNotBetween(String value1, String value2) {
            addCriterion("staff_native_place not between", value1, value2, "staffNativePlace");
            return (Criteria) this;
        }

        public Criteria andStaffTypeIdIsNull() {
            addCriterion("staff_type_id is null");
            return (Criteria) this;
        }

        public Criteria andStaffTypeIdIsNotNull() {
            addCriterion("staff_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andStaffTypeIdEqualTo(Integer value) {
            addCriterion("staff_type_id =", value, "staffTypeId");
            return (Criteria) this;
        }

        public Criteria andStaffTypeIdNotEqualTo(Integer value) {
            addCriterion("staff_type_id <>", value, "staffTypeId");
            return (Criteria) this;
        }

        public Criteria andStaffTypeIdGreaterThan(Integer value) {
            addCriterion("staff_type_id >", value, "staffTypeId");
            return (Criteria) this;
        }

        public Criteria andStaffTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("staff_type_id >=", value, "staffTypeId");
            return (Criteria) this;
        }

        public Criteria andStaffTypeIdLessThan(Integer value) {
            addCriterion("staff_type_id <", value, "staffTypeId");
            return (Criteria) this;
        }

        public Criteria andStaffTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("staff_type_id <=", value, "staffTypeId");
            return (Criteria) this;
        }

        public Criteria andStaffTypeIdIn(List<Integer> values) {
            addCriterion("staff_type_id in", values, "staffTypeId");
            return (Criteria) this;
        }

        public Criteria andStaffTypeIdNotIn(List<Integer> values) {
            addCriterion("staff_type_id not in", values, "staffTypeId");
            return (Criteria) this;
        }

        public Criteria andStaffTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("staff_type_id between", value1, value2, "staffTypeId");
            return (Criteria) this;
        }

        public Criteria andStaffTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("staff_type_id not between", value1, value2, "staffTypeId");
            return (Criteria) this;
        }

        public Criteria andIsPersonIsNull() {
            addCriterion("is_person is null");
            return (Criteria) this;
        }

        public Criteria andIsPersonIsNotNull() {
            addCriterion("is_person is not null");
            return (Criteria) this;
        }

        public Criteria andIsPersonEqualTo(Boolean value) {
            addCriterion("is_person =", value, "isPerson");
            return (Criteria) this;
        }

        public Criteria andIsPersonNotEqualTo(Boolean value) {
            addCriterion("is_person <>", value, "isPerson");
            return (Criteria) this;
        }

        public Criteria andIsPersonGreaterThan(Boolean value) {
            addCriterion("is_person >", value, "isPerson");
            return (Criteria) this;
        }

        public Criteria andIsPersonGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_person >=", value, "isPerson");
            return (Criteria) this;
        }

        public Criteria andIsPersonLessThan(Boolean value) {
            addCriterion("is_person <", value, "isPerson");
            return (Criteria) this;
        }

        public Criteria andIsPersonLessThanOrEqualTo(Boolean value) {
            addCriterion("is_person <=", value, "isPerson");
            return (Criteria) this;
        }

        public Criteria andIsPersonIn(List<Boolean> values) {
            addCriterion("is_person in", values, "isPerson");
            return (Criteria) this;
        }

        public Criteria andIsPersonNotIn(List<Boolean> values) {
            addCriterion("is_person not in", values, "isPerson");
            return (Criteria) this;
        }

        public Criteria andIsPersonBetween(Boolean value1, Boolean value2) {
            addCriterion("is_person between", value1, value2, "isPerson");
            return (Criteria) this;
        }

        public Criteria andIsPersonNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_person not between", value1, value2, "isPerson");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("group_id is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("group_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(Integer value) {
            addCriterion("group_id =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(Integer value) {
            addCriterion("group_id <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(Integer value) {
            addCriterion("group_id >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("group_id >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(Integer value) {
            addCriterion("group_id <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("group_id <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<Integer> values) {
            addCriterion("group_id in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<Integer> values) {
            addCriterion("group_id not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("group_id between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("group_id not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("dept_id is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("dept_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(Integer value) {
            addCriterion("dept_id =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(Integer value) {
            addCriterion("dept_id <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(Integer value) {
            addCriterion("dept_id >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("dept_id >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(Integer value) {
            addCriterion("dept_id <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(Integer value) {
            addCriterion("dept_id <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<Integer> values) {
            addCriterion("dept_id in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<Integer> values) {
            addCriterion("dept_id not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(Integer value1, Integer value2) {
            addCriterion("dept_id between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(Integer value1, Integer value2) {
            addCriterion("dept_id not between", value1, value2, "deptId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table staff
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table staff
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}