package com.zkxh.demo.model.staff;

import com.zkxh.demo.common.base.entity.BaseEntity;

import java.util.List;

public class StaffDept extends BaseEntity {

    private List<StaffGroup> staffGroupList;

    private List<Staff> staffList;

    public List<StaffGroup> getStaffGroupList() {
        return staffGroupList;
    }

    public void setStaffGroupList(List<StaffGroup> staffGroupList) {
        this.staffGroupList = staffGroupList;
    }

    public List<Staff> getStaffList() {
        return staffList;
    }

    public void setStaffList(List<Staff> staffList) {
        this.staffList = staffList;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_dept.dept_id
     *
     * @mbg.generated
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_dept.dept_name
     *
     * @mbg.generated
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_dept.dept_id
     *
     * @return the value of staff_dept.dept_id
     * @mbg.generated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_dept.dept_id
     *
     * @param deptId the value for staff_dept.dept_id
     * @mbg.generated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_dept.dept_name
     *
     * @return the value of staff_dept.dept_name
     * @mbg.generated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_dept.dept_name
     *
     * @param deptName the value for staff_dept.dept_name
     * @mbg.generated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}