package com.zkxh.demo.model.staff;

import com.zkxh.demo.common.base.entity.BaseEntity;
import com.zkxh.demo.dto.staff.StaffDto;

import java.util.List;

public class StaffGroup extends BaseEntity {


    private StaffDept staffDept;


    private List<StaffDto> staffList;

    public List<StaffDto> getStaffList() {
        return staffList;
    }

    public void setStaffList(List<StaffDto> staffList) {
        this.staffList = staffList;
    }

    public StaffDept getStaffDept() {
        return staffDept;
    }

    public void setStaffDept(StaffDept staffDept) {
        this.staffDept = staffDept;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_group.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_group.group_name
     *
     * @mbg.generated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_group.dept_id
     *
     * @mbg.generated
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_group.group_id
     *
     * @return the value of staff_group.group_id
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_group.group_id
     *
     * @param groupId the value for staff_group.group_id
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_group.group_name
     *
     * @return the value of staff_group.group_name
     * @mbg.generated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_group.group_name
     *
     * @param groupName the value for staff_group.group_name
     * @mbg.generated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_group.dept_id
     *
     * @return the value of staff_group.dept_id
     * @mbg.generated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_group.dept_id
     *
     * @param deptId the value for staff_group.dept_id
     * @mbg.generated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}