package com.zkxh.demo.model.rt_gas;

import com.zkxh.demo.common.base.entity.BaseEntity;

import java.util.Date;

public class RtGasInfo extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.rt_gas_info_id
     *
     * @mbg.generated
     */
    private Integer rtGasInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.co
     *
     * @mbg.generated
     */
    private Double co;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.co_unit
     *
     * @mbg.generated
     */
    private Integer coUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.ch4
     *
     * @mbg.generated
     */
    private Double ch4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.ch4_unit
     *
     * @mbg.generated
     */
    private Integer ch4Unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.o2
     *
     * @mbg.generated
     */
    private Double o2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.o2_unit
     *
     * @mbg.generated
     */
    private Integer o2Unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.t_co2
     *
     * @mbg.generated
     */
    private Double tCo2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.t_co2_unit
     *
     * @mbg.generated
     */
    private Integer tCo2Unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.t_temperature
     *
     * @mbg.generated
     */
    private Double tTemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.t_temperature_unit
     *
     * @mbg.generated
     */
    private Integer tTemperatureUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.t_humidity
     *
     * @mbg.generated
     */
    private Double tHumidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.t_humidity_unit
     *
     * @mbg.generated
     */
    private Integer tHumidityUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.t_field_3
     *
     * @mbg.generated
     */
    private Double tField3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.t_field_3_unit
     *
     * @mbg.generated
     */
    private Integer tField3Unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.terminal_id
     *
     * @mbg.generated
     */
    private String terminalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.station_id
     *
     * @mbg.generated
     */
    private String stationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.terminal_ip
     *
     * @mbg.generated
     */
    private String terminalIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.station_ip
     *
     * @mbg.generated
     */
    private String stationIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.terminal_real_time
     *
     * @mbg.generated
     */
    private Date terminalRealTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.info_type
     *
     * @mbg.generated
     */
    private Boolean infoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.sequence_id
     *
     * @mbg.generated
     */
    private String sequenceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.position_id
     *
     * @mbg.generated
     */
    private Integer positionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.rt_gas_info_id
     *
     * @return the value of rt_gas_info.rt_gas_info_id
     * @mbg.generated
     */
    public Integer getRtGasInfoId() {
        return rtGasInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.rt_gas_info_id
     *
     * @param rtGasInfoId the value for rt_gas_info.rt_gas_info_id
     * @mbg.generated
     */
    public void setRtGasInfoId(Integer rtGasInfoId) {
        this.rtGasInfoId = rtGasInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.co
     *
     * @return the value of rt_gas_info.co
     * @mbg.generated
     */
    public Double getCo() {
        return co;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.co
     *
     * @param co the value for rt_gas_info.co
     * @mbg.generated
     */
    public void setCo(Double co) {
        this.co = co;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.co_unit
     *
     * @return the value of rt_gas_info.co_unit
     * @mbg.generated
     */
    public Integer getCoUnit() {
        return coUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.co_unit
     *
     * @param coUnit the value for rt_gas_info.co_unit
     * @mbg.generated
     */
    public void setCoUnit(Integer coUnit) {
        this.coUnit = coUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.ch4
     *
     * @return the value of rt_gas_info.ch4
     * @mbg.generated
     */
    public Double getCh4() {
        return ch4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.ch4
     *
     * @param ch4 the value for rt_gas_info.ch4
     * @mbg.generated
     */
    public void setCh4(Double ch4) {
        this.ch4 = ch4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.ch4_unit
     *
     * @return the value of rt_gas_info.ch4_unit
     * @mbg.generated
     */
    public Integer getCh4Unit() {
        return ch4Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.ch4_unit
     *
     * @param ch4Unit the value for rt_gas_info.ch4_unit
     * @mbg.generated
     */
    public void setCh4Unit(Integer ch4Unit) {
        this.ch4Unit = ch4Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.o2
     *
     * @return the value of rt_gas_info.o2
     * @mbg.generated
     */
    public Double getO2() {
        return o2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.o2
     *
     * @param o2 the value for rt_gas_info.o2
     * @mbg.generated
     */
    public void setO2(Double o2) {
        this.o2 = o2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.o2_unit
     *
     * @return the value of rt_gas_info.o2_unit
     * @mbg.generated
     */
    public Integer getO2Unit() {
        return o2Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.o2_unit
     *
     * @param o2Unit the value for rt_gas_info.o2_unit
     * @mbg.generated
     */
    public void setO2Unit(Integer o2Unit) {
        this.o2Unit = o2Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.t_co2
     *
     * @return the value of rt_gas_info.t_co2
     * @mbg.generated
     */
    public Double gettCo2() {
        return tCo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.t_co2
     *
     * @param tCo2 the value for rt_gas_info.t_co2
     * @mbg.generated
     */
    public void settCo2(Double tCo2) {
        this.tCo2 = tCo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.t_co2_unit
     *
     * @return the value of rt_gas_info.t_co2_unit
     * @mbg.generated
     */
    public Integer gettCo2Unit() {
        return tCo2Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.t_co2_unit
     *
     * @param tCo2Unit the value for rt_gas_info.t_co2_unit
     * @mbg.generated
     */
    public void settCo2Unit(Integer tCo2Unit) {
        this.tCo2Unit = tCo2Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.t_temperature
     *
     * @return the value of rt_gas_info.t_temperature
     * @mbg.generated
     */
    public Double gettTemperature() {
        return tTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.t_temperature
     *
     * @param tTemperature the value for rt_gas_info.t_temperature
     * @mbg.generated
     */
    public void settTemperature(Double tTemperature) {
        this.tTemperature = tTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.t_temperature_unit
     *
     * @return the value of rt_gas_info.t_temperature_unit
     * @mbg.generated
     */
    public Integer gettTemperatureUnit() {
        return tTemperatureUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.t_temperature_unit
     *
     * @param tTemperatureUnit the value for rt_gas_info.t_temperature_unit
     * @mbg.generated
     */
    public void settTemperatureUnit(Integer tTemperatureUnit) {
        this.tTemperatureUnit = tTemperatureUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.t_humidity
     *
     * @return the value of rt_gas_info.t_humidity
     * @mbg.generated
     */
    public Double gettHumidity() {
        return tHumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.t_humidity
     *
     * @param tHumidity the value for rt_gas_info.t_humidity
     * @mbg.generated
     */
    public void settHumidity(Double tHumidity) {
        this.tHumidity = tHumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.t_humidity_unit
     *
     * @return the value of rt_gas_info.t_humidity_unit
     * @mbg.generated
     */
    public Integer gettHumidityUnit() {
        return tHumidityUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.t_humidity_unit
     *
     * @param tHumidityUnit the value for rt_gas_info.t_humidity_unit
     * @mbg.generated
     */
    public void settHumidityUnit(Integer tHumidityUnit) {
        this.tHumidityUnit = tHumidityUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.t_field_3
     *
     * @return the value of rt_gas_info.t_field_3
     * @mbg.generated
     */
    public Double gettField3() {
        return tField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.t_field_3
     *
     * @param tField3 the value for rt_gas_info.t_field_3
     * @mbg.generated
     */
    public void settField3(Double tField3) {
        this.tField3 = tField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.t_field_3_unit
     *
     * @return the value of rt_gas_info.t_field_3_unit
     * @mbg.generated
     */
    public Integer gettField3Unit() {
        return tField3Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.t_field_3_unit
     *
     * @param tField3Unit the value for rt_gas_info.t_field_3_unit
     * @mbg.generated
     */
    public void settField3Unit(Integer tField3Unit) {
        this.tField3Unit = tField3Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.create_time
     *
     * @return the value of rt_gas_info.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.create_time
     *
     * @param createTime the value for rt_gas_info.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.terminal_id
     *
     * @return the value of rt_gas_info.terminal_id
     * @mbg.generated
     */
    public String getTerminalId() {
        return terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.terminal_id
     *
     * @param terminalId the value for rt_gas_info.terminal_id
     * @mbg.generated
     */
    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId == null ? null : terminalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.station_id
     *
     * @return the value of rt_gas_info.station_id
     * @mbg.generated
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.station_id
     *
     * @param stationId the value for rt_gas_info.station_id
     * @mbg.generated
     */
    public void setStationId(String stationId) {
        this.stationId = stationId == null ? null : stationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.terminal_ip
     *
     * @return the value of rt_gas_info.terminal_ip
     * @mbg.generated
     */
    public String getTerminalIp() {
        return terminalIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.terminal_ip
     *
     * @param terminalIp the value for rt_gas_info.terminal_ip
     * @mbg.generated
     */
    public void setTerminalIp(String terminalIp) {
        this.terminalIp = terminalIp == null ? null : terminalIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.station_ip
     *
     * @return the value of rt_gas_info.station_ip
     * @mbg.generated
     */
    public String getStationIp() {
        return stationIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.station_ip
     *
     * @param stationIp the value for rt_gas_info.station_ip
     * @mbg.generated
     */
    public void setStationIp(String stationIp) {
        this.stationIp = stationIp == null ? null : stationIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.terminal_real_time
     *
     * @return the value of rt_gas_info.terminal_real_time
     * @mbg.generated
     */
    public Date getTerminalRealTime() {
        return terminalRealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.terminal_real_time
     *
     * @param terminalRealTime the value for rt_gas_info.terminal_real_time
     * @mbg.generated
     */
    public void setTerminalRealTime(Date terminalRealTime) {
        this.terminalRealTime = terminalRealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.info_type
     *
     * @return the value of rt_gas_info.info_type
     * @mbg.generated
     */
    public Boolean getInfoType() {
        return infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.info_type
     *
     * @param infoType the value for rt_gas_info.info_type
     * @mbg.generated
     */
    public void setInfoType(Boolean infoType) {
        this.infoType = infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.sequence_id
     *
     * @return the value of rt_gas_info.sequence_id
     * @mbg.generated
     */
    public String getSequenceId() {
        return sequenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.sequence_id
     *
     * @param sequenceId the value for rt_gas_info.sequence_id
     * @mbg.generated
     */
    public void setSequenceId(String sequenceId) {
        this.sequenceId = sequenceId == null ? null : sequenceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.position_id
     *
     * @return the value of rt_gas_info.position_id
     * @mbg.generated
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.position_id
     *
     * @param positionId the value for rt_gas_info.position_id
     * @mbg.generated
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }
}