package com.zkxh.demo.model.rt_gas;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RtGasInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    public RtGasInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRtGasInfoIdIsNull() {
            addCriterion("rt_gas_info_id is null");
            return (Criteria) this;
        }

        public Criteria andRtGasInfoIdIsNotNull() {
            addCriterion("rt_gas_info_id is not null");
            return (Criteria) this;
        }

        public Criteria andRtGasInfoIdEqualTo(Integer value) {
            addCriterion("rt_gas_info_id =", value, "rtGasInfoId");
            return (Criteria) this;
        }

        public Criteria andRtGasInfoIdNotEqualTo(Integer value) {
            addCriterion("rt_gas_info_id <>", value, "rtGasInfoId");
            return (Criteria) this;
        }

        public Criteria andRtGasInfoIdGreaterThan(Integer value) {
            addCriterion("rt_gas_info_id >", value, "rtGasInfoId");
            return (Criteria) this;
        }

        public Criteria andRtGasInfoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("rt_gas_info_id >=", value, "rtGasInfoId");
            return (Criteria) this;
        }

        public Criteria andRtGasInfoIdLessThan(Integer value) {
            addCriterion("rt_gas_info_id <", value, "rtGasInfoId");
            return (Criteria) this;
        }

        public Criteria andRtGasInfoIdLessThanOrEqualTo(Integer value) {
            addCriterion("rt_gas_info_id <=", value, "rtGasInfoId");
            return (Criteria) this;
        }

        public Criteria andRtGasInfoIdIn(List<Integer> values) {
            addCriterion("rt_gas_info_id in", values, "rtGasInfoId");
            return (Criteria) this;
        }

        public Criteria andRtGasInfoIdNotIn(List<Integer> values) {
            addCriterion("rt_gas_info_id not in", values, "rtGasInfoId");
            return (Criteria) this;
        }

        public Criteria andRtGasInfoIdBetween(Integer value1, Integer value2) {
            addCriterion("rt_gas_info_id between", value1, value2, "rtGasInfoId");
            return (Criteria) this;
        }

        public Criteria andRtGasInfoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("rt_gas_info_id not between", value1, value2, "rtGasInfoId");
            return (Criteria) this;
        }

        public Criteria andCoIsNull() {
            addCriterion("co is null");
            return (Criteria) this;
        }

        public Criteria andCoIsNotNull() {
            addCriterion("co is not null");
            return (Criteria) this;
        }

        public Criteria andCoEqualTo(Double value) {
            addCriterion("co =", value, "co");
            return (Criteria) this;
        }

        public Criteria andCoNotEqualTo(Double value) {
            addCriterion("co <>", value, "co");
            return (Criteria) this;
        }

        public Criteria andCoGreaterThan(Double value) {
            addCriterion("co >", value, "co");
            return (Criteria) this;
        }

        public Criteria andCoGreaterThanOrEqualTo(Double value) {
            addCriterion("co >=", value, "co");
            return (Criteria) this;
        }

        public Criteria andCoLessThan(Double value) {
            addCriterion("co <", value, "co");
            return (Criteria) this;
        }

        public Criteria andCoLessThanOrEqualTo(Double value) {
            addCriterion("co <=", value, "co");
            return (Criteria) this;
        }

        public Criteria andCoIn(List<Double> values) {
            addCriterion("co in", values, "co");
            return (Criteria) this;
        }

        public Criteria andCoNotIn(List<Double> values) {
            addCriterion("co not in", values, "co");
            return (Criteria) this;
        }

        public Criteria andCoBetween(Double value1, Double value2) {
            addCriterion("co between", value1, value2, "co");
            return (Criteria) this;
        }

        public Criteria andCoNotBetween(Double value1, Double value2) {
            addCriterion("co not between", value1, value2, "co");
            return (Criteria) this;
        }

        public Criteria andCoUnitIsNull() {
            addCriterion("co_unit is null");
            return (Criteria) this;
        }

        public Criteria andCoUnitIsNotNull() {
            addCriterion("co_unit is not null");
            return (Criteria) this;
        }

        public Criteria andCoUnitEqualTo(Integer value) {
            addCriterion("co_unit =", value, "coUnit");
            return (Criteria) this;
        }

        public Criteria andCoUnitNotEqualTo(Integer value) {
            addCriterion("co_unit <>", value, "coUnit");
            return (Criteria) this;
        }

        public Criteria andCoUnitGreaterThan(Integer value) {
            addCriterion("co_unit >", value, "coUnit");
            return (Criteria) this;
        }

        public Criteria andCoUnitGreaterThanOrEqualTo(Integer value) {
            addCriterion("co_unit >=", value, "coUnit");
            return (Criteria) this;
        }

        public Criteria andCoUnitLessThan(Integer value) {
            addCriterion("co_unit <", value, "coUnit");
            return (Criteria) this;
        }

        public Criteria andCoUnitLessThanOrEqualTo(Integer value) {
            addCriterion("co_unit <=", value, "coUnit");
            return (Criteria) this;
        }

        public Criteria andCoUnitIn(List<Integer> values) {
            addCriterion("co_unit in", values, "coUnit");
            return (Criteria) this;
        }

        public Criteria andCoUnitNotIn(List<Integer> values) {
            addCriterion("co_unit not in", values, "coUnit");
            return (Criteria) this;
        }

        public Criteria andCoUnitBetween(Integer value1, Integer value2) {
            addCriterion("co_unit between", value1, value2, "coUnit");
            return (Criteria) this;
        }

        public Criteria andCoUnitNotBetween(Integer value1, Integer value2) {
            addCriterion("co_unit not between", value1, value2, "coUnit");
            return (Criteria) this;
        }

        public Criteria andCh4IsNull() {
            addCriterion("ch4 is null");
            return (Criteria) this;
        }

        public Criteria andCh4IsNotNull() {
            addCriterion("ch4 is not null");
            return (Criteria) this;
        }

        public Criteria andCh4EqualTo(Double value) {
            addCriterion("ch4 =", value, "ch4");
            return (Criteria) this;
        }

        public Criteria andCh4NotEqualTo(Double value) {
            addCriterion("ch4 <>", value, "ch4");
            return (Criteria) this;
        }

        public Criteria andCh4GreaterThan(Double value) {
            addCriterion("ch4 >", value, "ch4");
            return (Criteria) this;
        }

        public Criteria andCh4GreaterThanOrEqualTo(Double value) {
            addCriterion("ch4 >=", value, "ch4");
            return (Criteria) this;
        }

        public Criteria andCh4LessThan(Double value) {
            addCriterion("ch4 <", value, "ch4");
            return (Criteria) this;
        }

        public Criteria andCh4LessThanOrEqualTo(Double value) {
            addCriterion("ch4 <=", value, "ch4");
            return (Criteria) this;
        }

        public Criteria andCh4In(List<Double> values) {
            addCriterion("ch4 in", values, "ch4");
            return (Criteria) this;
        }

        public Criteria andCh4NotIn(List<Double> values) {
            addCriterion("ch4 not in", values, "ch4");
            return (Criteria) this;
        }

        public Criteria andCh4Between(Double value1, Double value2) {
            addCriterion("ch4 between", value1, value2, "ch4");
            return (Criteria) this;
        }

        public Criteria andCh4NotBetween(Double value1, Double value2) {
            addCriterion("ch4 not between", value1, value2, "ch4");
            return (Criteria) this;
        }

        public Criteria andCh4UnitIsNull() {
            addCriterion("ch4_unit is null");
            return (Criteria) this;
        }

        public Criteria andCh4UnitIsNotNull() {
            addCriterion("ch4_unit is not null");
            return (Criteria) this;
        }

        public Criteria andCh4UnitEqualTo(Integer value) {
            addCriterion("ch4_unit =", value, "ch4Unit");
            return (Criteria) this;
        }

        public Criteria andCh4UnitNotEqualTo(Integer value) {
            addCriterion("ch4_unit <>", value, "ch4Unit");
            return (Criteria) this;
        }

        public Criteria andCh4UnitGreaterThan(Integer value) {
            addCriterion("ch4_unit >", value, "ch4Unit");
            return (Criteria) this;
        }

        public Criteria andCh4UnitGreaterThanOrEqualTo(Integer value) {
            addCriterion("ch4_unit >=", value, "ch4Unit");
            return (Criteria) this;
        }

        public Criteria andCh4UnitLessThan(Integer value) {
            addCriterion("ch4_unit <", value, "ch4Unit");
            return (Criteria) this;
        }

        public Criteria andCh4UnitLessThanOrEqualTo(Integer value) {
            addCriterion("ch4_unit <=", value, "ch4Unit");
            return (Criteria) this;
        }

        public Criteria andCh4UnitIn(List<Integer> values) {
            addCriterion("ch4_unit in", values, "ch4Unit");
            return (Criteria) this;
        }

        public Criteria andCh4UnitNotIn(List<Integer> values) {
            addCriterion("ch4_unit not in", values, "ch4Unit");
            return (Criteria) this;
        }

        public Criteria andCh4UnitBetween(Integer value1, Integer value2) {
            addCriterion("ch4_unit between", value1, value2, "ch4Unit");
            return (Criteria) this;
        }

        public Criteria andCh4UnitNotBetween(Integer value1, Integer value2) {
            addCriterion("ch4_unit not between", value1, value2, "ch4Unit");
            return (Criteria) this;
        }

        public Criteria andO2IsNull() {
            addCriterion("o2 is null");
            return (Criteria) this;
        }

        public Criteria andO2IsNotNull() {
            addCriterion("o2 is not null");
            return (Criteria) this;
        }

        public Criteria andO2EqualTo(Double value) {
            addCriterion("o2 =", value, "o2");
            return (Criteria) this;
        }

        public Criteria andO2NotEqualTo(Double value) {
            addCriterion("o2 <>", value, "o2");
            return (Criteria) this;
        }

        public Criteria andO2GreaterThan(Double value) {
            addCriterion("o2 >", value, "o2");
            return (Criteria) this;
        }

        public Criteria andO2GreaterThanOrEqualTo(Double value) {
            addCriterion("o2 >=", value, "o2");
            return (Criteria) this;
        }

        public Criteria andO2LessThan(Double value) {
            addCriterion("o2 <", value, "o2");
            return (Criteria) this;
        }

        public Criteria andO2LessThanOrEqualTo(Double value) {
            addCriterion("o2 <=", value, "o2");
            return (Criteria) this;
        }

        public Criteria andO2In(List<Double> values) {
            addCriterion("o2 in", values, "o2");
            return (Criteria) this;
        }

        public Criteria andO2NotIn(List<Double> values) {
            addCriterion("o2 not in", values, "o2");
            return (Criteria) this;
        }

        public Criteria andO2Between(Double value1, Double value2) {
            addCriterion("o2 between", value1, value2, "o2");
            return (Criteria) this;
        }

        public Criteria andO2NotBetween(Double value1, Double value2) {
            addCriterion("o2 not between", value1, value2, "o2");
            return (Criteria) this;
        }

        public Criteria andO2UnitIsNull() {
            addCriterion("o2_unit is null");
            return (Criteria) this;
        }

        public Criteria andO2UnitIsNotNull() {
            addCriterion("o2_unit is not null");
            return (Criteria) this;
        }

        public Criteria andO2UnitEqualTo(Integer value) {
            addCriterion("o2_unit =", value, "o2Unit");
            return (Criteria) this;
        }

        public Criteria andO2UnitNotEqualTo(Integer value) {
            addCriterion("o2_unit <>", value, "o2Unit");
            return (Criteria) this;
        }

        public Criteria andO2UnitGreaterThan(Integer value) {
            addCriterion("o2_unit >", value, "o2Unit");
            return (Criteria) this;
        }

        public Criteria andO2UnitGreaterThanOrEqualTo(Integer value) {
            addCriterion("o2_unit >=", value, "o2Unit");
            return (Criteria) this;
        }

        public Criteria andO2UnitLessThan(Integer value) {
            addCriterion("o2_unit <", value, "o2Unit");
            return (Criteria) this;
        }

        public Criteria andO2UnitLessThanOrEqualTo(Integer value) {
            addCriterion("o2_unit <=", value, "o2Unit");
            return (Criteria) this;
        }

        public Criteria andO2UnitIn(List<Integer> values) {
            addCriterion("o2_unit in", values, "o2Unit");
            return (Criteria) this;
        }

        public Criteria andO2UnitNotIn(List<Integer> values) {
            addCriterion("o2_unit not in", values, "o2Unit");
            return (Criteria) this;
        }

        public Criteria andO2UnitBetween(Integer value1, Integer value2) {
            addCriterion("o2_unit between", value1, value2, "o2Unit");
            return (Criteria) this;
        }

        public Criteria andO2UnitNotBetween(Integer value1, Integer value2) {
            addCriterion("o2_unit not between", value1, value2, "o2Unit");
            return (Criteria) this;
        }

        public Criteria andCo2IsNull() {
            addCriterion("co2 is null");
            return (Criteria) this;
        }

        public Criteria andCo2IsNotNull() {
            addCriterion("co2 is not null");
            return (Criteria) this;
        }

        public Criteria andCo2EqualTo(Double value) {
            addCriterion("co2 =", value, "co2");
            return (Criteria) this;
        }

        public Criteria andCo2NotEqualTo(Double value) {
            addCriterion("co2 <>", value, "co2");
            return (Criteria) this;
        }

        public Criteria andCo2GreaterThan(Double value) {
            addCriterion("co2 >", value, "co2");
            return (Criteria) this;
        }

        public Criteria andCo2GreaterThanOrEqualTo(Double value) {
            addCriterion("co2 >=", value, "co2");
            return (Criteria) this;
        }

        public Criteria andCo2LessThan(Double value) {
            addCriterion("co2 <", value, "co2");
            return (Criteria) this;
        }

        public Criteria andCo2LessThanOrEqualTo(Double value) {
            addCriterion("co2 <=", value, "co2");
            return (Criteria) this;
        }

        public Criteria andCo2In(List<Double> values) {
            addCriterion("co2 in", values, "co2");
            return (Criteria) this;
        }

        public Criteria andCo2NotIn(List<Double> values) {
            addCriterion("co2 not in", values, "co2");
            return (Criteria) this;
        }

        public Criteria andCo2Between(Double value1, Double value2) {
            addCriterion("co2 between", value1, value2, "co2");
            return (Criteria) this;
        }

        public Criteria andCo2NotBetween(Double value1, Double value2) {
            addCriterion("co2 not between", value1, value2, "co2");
            return (Criteria) this;
        }

        public Criteria andCo2UnitIsNull() {
            addCriterion("co2_unit is null");
            return (Criteria) this;
        }

        public Criteria andCo2UnitIsNotNull() {
            addCriterion("co2_unit is not null");
            return (Criteria) this;
        }

        public Criteria andCo2UnitEqualTo(Integer value) {
            addCriterion("co2_unit =", value, "co2Unit");
            return (Criteria) this;
        }

        public Criteria andCo2UnitNotEqualTo(Integer value) {
            addCriterion("co2_unit <>", value, "co2Unit");
            return (Criteria) this;
        }

        public Criteria andCo2UnitGreaterThan(Integer value) {
            addCriterion("co2_unit >", value, "co2Unit");
            return (Criteria) this;
        }

        public Criteria andCo2UnitGreaterThanOrEqualTo(Integer value) {
            addCriterion("co2_unit >=", value, "co2Unit");
            return (Criteria) this;
        }

        public Criteria andCo2UnitLessThan(Integer value) {
            addCriterion("co2_unit <", value, "co2Unit");
            return (Criteria) this;
        }

        public Criteria andCo2UnitLessThanOrEqualTo(Integer value) {
            addCriterion("co2_unit <=", value, "co2Unit");
            return (Criteria) this;
        }

        public Criteria andCo2UnitIn(List<Integer> values) {
            addCriterion("co2_unit in", values, "co2Unit");
            return (Criteria) this;
        }

        public Criteria andCo2UnitNotIn(List<Integer> values) {
            addCriterion("co2_unit not in", values, "co2Unit");
            return (Criteria) this;
        }

        public Criteria andCo2UnitBetween(Integer value1, Integer value2) {
            addCriterion("co2_unit between", value1, value2, "co2Unit");
            return (Criteria) this;
        }

        public Criteria andCo2UnitNotBetween(Integer value1, Integer value2) {
            addCriterion("co2_unit not between", value1, value2, "co2Unit");
            return (Criteria) this;
        }

        public Criteria andTemperatureIsNull() {
            addCriterion("temperature is null");
            return (Criteria) this;
        }

        public Criteria andTemperatureIsNotNull() {
            addCriterion("temperature is not null");
            return (Criteria) this;
        }

        public Criteria andTemperatureEqualTo(Double value) {
            addCriterion("temperature =", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotEqualTo(Double value) {
            addCriterion("temperature <>", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureGreaterThan(Double value) {
            addCriterion("temperature >", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureGreaterThanOrEqualTo(Double value) {
            addCriterion("temperature >=", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureLessThan(Double value) {
            addCriterion("temperature <", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureLessThanOrEqualTo(Double value) {
            addCriterion("temperature <=", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureIn(List<Double> values) {
            addCriterion("temperature in", values, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotIn(List<Double> values) {
            addCriterion("temperature not in", values, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureBetween(Double value1, Double value2) {
            addCriterion("temperature between", value1, value2, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotBetween(Double value1, Double value2) {
            addCriterion("temperature not between", value1, value2, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureUnitIsNull() {
            addCriterion("temperature_unit is null");
            return (Criteria) this;
        }

        public Criteria andTemperatureUnitIsNotNull() {
            addCriterion("temperature_unit is not null");
            return (Criteria) this;
        }

        public Criteria andTemperatureUnitEqualTo(Integer value) {
            addCriterion("temperature_unit =", value, "temperatureUnit");
            return (Criteria) this;
        }

        public Criteria andTemperatureUnitNotEqualTo(Integer value) {
            addCriterion("temperature_unit <>", value, "temperatureUnit");
            return (Criteria) this;
        }

        public Criteria andTemperatureUnitGreaterThan(Integer value) {
            addCriterion("temperature_unit >", value, "temperatureUnit");
            return (Criteria) this;
        }

        public Criteria andTemperatureUnitGreaterThanOrEqualTo(Integer value) {
            addCriterion("temperature_unit >=", value, "temperatureUnit");
            return (Criteria) this;
        }

        public Criteria andTemperatureUnitLessThan(Integer value) {
            addCriterion("temperature_unit <", value, "temperatureUnit");
            return (Criteria) this;
        }

        public Criteria andTemperatureUnitLessThanOrEqualTo(Integer value) {
            addCriterion("temperature_unit <=", value, "temperatureUnit");
            return (Criteria) this;
        }

        public Criteria andTemperatureUnitIn(List<Integer> values) {
            addCriterion("temperature_unit in", values, "temperatureUnit");
            return (Criteria) this;
        }

        public Criteria andTemperatureUnitNotIn(List<Integer> values) {
            addCriterion("temperature_unit not in", values, "temperatureUnit");
            return (Criteria) this;
        }

        public Criteria andTemperatureUnitBetween(Integer value1, Integer value2) {
            addCriterion("temperature_unit between", value1, value2, "temperatureUnit");
            return (Criteria) this;
        }

        public Criteria andTemperatureUnitNotBetween(Integer value1, Integer value2) {
            addCriterion("temperature_unit not between", value1, value2, "temperatureUnit");
            return (Criteria) this;
        }

        public Criteria andHumidityIsNull() {
            addCriterion("humidity is null");
            return (Criteria) this;
        }

        public Criteria andHumidityIsNotNull() {
            addCriterion("humidity is not null");
            return (Criteria) this;
        }

        public Criteria andHumidityEqualTo(Double value) {
            addCriterion("humidity =", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityNotEqualTo(Double value) {
            addCriterion("humidity <>", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityGreaterThan(Double value) {
            addCriterion("humidity >", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityGreaterThanOrEqualTo(Double value) {
            addCriterion("humidity >=", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityLessThan(Double value) {
            addCriterion("humidity <", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityLessThanOrEqualTo(Double value) {
            addCriterion("humidity <=", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityIn(List<Double> values) {
            addCriterion("humidity in", values, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityNotIn(List<Double> values) {
            addCriterion("humidity not in", values, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityBetween(Double value1, Double value2) {
            addCriterion("humidity between", value1, value2, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityNotBetween(Double value1, Double value2) {
            addCriterion("humidity not between", value1, value2, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityUnitIsNull() {
            addCriterion("humidity_unit is null");
            return (Criteria) this;
        }

        public Criteria andHumidityUnitIsNotNull() {
            addCriterion("humidity_unit is not null");
            return (Criteria) this;
        }

        public Criteria andHumidityUnitEqualTo(Integer value) {
            addCriterion("humidity_unit =", value, "humidityUnit");
            return (Criteria) this;
        }

        public Criteria andHumidityUnitNotEqualTo(Integer value) {
            addCriterion("humidity_unit <>", value, "humidityUnit");
            return (Criteria) this;
        }

        public Criteria andHumidityUnitGreaterThan(Integer value) {
            addCriterion("humidity_unit >", value, "humidityUnit");
            return (Criteria) this;
        }

        public Criteria andHumidityUnitGreaterThanOrEqualTo(Integer value) {
            addCriterion("humidity_unit >=", value, "humidityUnit");
            return (Criteria) this;
        }

        public Criteria andHumidityUnitLessThan(Integer value) {
            addCriterion("humidity_unit <", value, "humidityUnit");
            return (Criteria) this;
        }

        public Criteria andHumidityUnitLessThanOrEqualTo(Integer value) {
            addCriterion("humidity_unit <=", value, "humidityUnit");
            return (Criteria) this;
        }

        public Criteria andHumidityUnitIn(List<Integer> values) {
            addCriterion("humidity_unit in", values, "humidityUnit");
            return (Criteria) this;
        }

        public Criteria andHumidityUnitNotIn(List<Integer> values) {
            addCriterion("humidity_unit not in", values, "humidityUnit");
            return (Criteria) this;
        }

        public Criteria andHumidityUnitBetween(Integer value1, Integer value2) {
            addCriterion("humidity_unit between", value1, value2, "humidityUnit");
            return (Criteria) this;
        }

        public Criteria andHumidityUnitNotBetween(Integer value1, Integer value2) {
            addCriterion("humidity_unit not between", value1, value2, "humidityUnit");
            return (Criteria) this;
        }

        public Criteria andField3IsNull() {
            addCriterion("field_3 is null");
            return (Criteria) this;
        }

        public Criteria andField3IsNotNull() {
            addCriterion("field_3 is not null");
            return (Criteria) this;
        }

        public Criteria andField3EqualTo(Double value) {
            addCriterion("field_3 =", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3NotEqualTo(Double value) {
            addCriterion("field_3 <>", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3GreaterThan(Double value) {
            addCriterion("field_3 >", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3GreaterThanOrEqualTo(Double value) {
            addCriterion("field_3 >=", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3LessThan(Double value) {
            addCriterion("field_3 <", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3LessThanOrEqualTo(Double value) {
            addCriterion("field_3 <=", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3In(List<Double> values) {
            addCriterion("field_3 in", values, "field3");
            return (Criteria) this;
        }

        public Criteria andField3NotIn(List<Double> values) {
            addCriterion("field_3 not in", values, "field3");
            return (Criteria) this;
        }

        public Criteria andField3Between(Double value1, Double value2) {
            addCriterion("field_3 between", value1, value2, "field3");
            return (Criteria) this;
        }

        public Criteria andField3NotBetween(Double value1, Double value2) {
            addCriterion("field_3 not between", value1, value2, "field3");
            return (Criteria) this;
        }

        public Criteria andField3UnitIsNull() {
            addCriterion("field_3_unit is null");
            return (Criteria) this;
        }

        public Criteria andField3UnitIsNotNull() {
            addCriterion("field_3_unit is not null");
            return (Criteria) this;
        }

        public Criteria andField3UnitEqualTo(Integer value) {
            addCriterion("field_3_unit =", value, "field3Unit");
            return (Criteria) this;
        }

        public Criteria andField3UnitNotEqualTo(Integer value) {
            addCriterion("field_3_unit <>", value, "field3Unit");
            return (Criteria) this;
        }

        public Criteria andField3UnitGreaterThan(Integer value) {
            addCriterion("field_3_unit >", value, "field3Unit");
            return (Criteria) this;
        }

        public Criteria andField3UnitGreaterThanOrEqualTo(Integer value) {
            addCriterion("field_3_unit >=", value, "field3Unit");
            return (Criteria) this;
        }

        public Criteria andField3UnitLessThan(Integer value) {
            addCriterion("field_3_unit <", value, "field3Unit");
            return (Criteria) this;
        }

        public Criteria andField3UnitLessThanOrEqualTo(Integer value) {
            addCriterion("field_3_unit <=", value, "field3Unit");
            return (Criteria) this;
        }

        public Criteria andField3UnitIn(List<Integer> values) {
            addCriterion("field_3_unit in", values, "field3Unit");
            return (Criteria) this;
        }

        public Criteria andField3UnitNotIn(List<Integer> values) {
            addCriterion("field_3_unit not in", values, "field3Unit");
            return (Criteria) this;
        }

        public Criteria andField3UnitBetween(Integer value1, Integer value2) {
            addCriterion("field_3_unit between", value1, value2, "field3Unit");
            return (Criteria) this;
        }

        public Criteria andField3UnitNotBetween(Integer value1, Integer value2) {
            addCriterion("field_3_unit not between", value1, value2, "field3Unit");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andTerminalIdIsNull() {
            addCriterion("terminal_id is null");
            return (Criteria) this;
        }

        public Criteria andTerminalIdIsNotNull() {
            addCriterion("terminal_id is not null");
            return (Criteria) this;
        }

        public Criteria andTerminalIdEqualTo(Integer value) {
            addCriterion("terminal_id =", value, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdNotEqualTo(Integer value) {
            addCriterion("terminal_id <>", value, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdGreaterThan(Integer value) {
            addCriterion("terminal_id >", value, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("terminal_id >=", value, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdLessThan(Integer value) {
            addCriterion("terminal_id <", value, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdLessThanOrEqualTo(Integer value) {
            addCriterion("terminal_id <=", value, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdIn(List<Integer> values) {
            addCriterion("terminal_id in", values, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdNotIn(List<Integer> values) {
            addCriterion("terminal_id not in", values, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdBetween(Integer value1, Integer value2) {
            addCriterion("terminal_id between", value1, value2, "terminalId");
            return (Criteria) this;
        }

        public Criteria andTerminalIdNotBetween(Integer value1, Integer value2) {
            addCriterion("terminal_id not between", value1, value2, "terminalId");
            return (Criteria) this;
        }

        public Criteria andStationIdIsNull() {
            addCriterion("station_id is null");
            return (Criteria) this;
        }

        public Criteria andStationIdIsNotNull() {
            addCriterion("station_id is not null");
            return (Criteria) this;
        }

        public Criteria andStationIdEqualTo(Integer value) {
            addCriterion("station_id =", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotEqualTo(Integer value) {
            addCriterion("station_id <>", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdGreaterThan(Integer value) {
            addCriterion("station_id >", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("station_id >=", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLessThan(Integer value) {
            addCriterion("station_id <", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLessThanOrEqualTo(Integer value) {
            addCriterion("station_id <=", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdIn(List<Integer> values) {
            addCriterion("station_id in", values, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotIn(List<Integer> values) {
            addCriterion("station_id not in", values, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdBetween(Integer value1, Integer value2) {
            addCriterion("station_id between", value1, value2, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotBetween(Integer value1, Integer value2) {
            addCriterion("station_id not between", value1, value2, "stationId");
            return (Criteria) this;
        }

        public Criteria andTerminalIpIsNull() {
            addCriterion("terminal_ip is null");
            return (Criteria) this;
        }

        public Criteria andTerminalIpIsNotNull() {
            addCriterion("terminal_ip is not null");
            return (Criteria) this;
        }

        public Criteria andTerminalIpEqualTo(String value) {
            addCriterion("terminal_ip =", value, "terminalIp");
            return (Criteria) this;
        }

        public Criteria andTerminalIpNotEqualTo(String value) {
            addCriterion("terminal_ip <>", value, "terminalIp");
            return (Criteria) this;
        }

        public Criteria andTerminalIpGreaterThan(String value) {
            addCriterion("terminal_ip >", value, "terminalIp");
            return (Criteria) this;
        }

        public Criteria andTerminalIpGreaterThanOrEqualTo(String value) {
            addCriterion("terminal_ip >=", value, "terminalIp");
            return (Criteria) this;
        }

        public Criteria andTerminalIpLessThan(String value) {
            addCriterion("terminal_ip <", value, "terminalIp");
            return (Criteria) this;
        }

        public Criteria andTerminalIpLessThanOrEqualTo(String value) {
            addCriterion("terminal_ip <=", value, "terminalIp");
            return (Criteria) this;
        }

        public Criteria andTerminalIpLike(String value) {
            addCriterion("terminal_ip like", value, "terminalIp");
            return (Criteria) this;
        }

        public Criteria andTerminalIpNotLike(String value) {
            addCriterion("terminal_ip not like", value, "terminalIp");
            return (Criteria) this;
        }

        public Criteria andTerminalIpIn(List<String> values) {
            addCriterion("terminal_ip in", values, "terminalIp");
            return (Criteria) this;
        }

        public Criteria andTerminalIpNotIn(List<String> values) {
            addCriterion("terminal_ip not in", values, "terminalIp");
            return (Criteria) this;
        }

        public Criteria andTerminalIpBetween(String value1, String value2) {
            addCriterion("terminal_ip between", value1, value2, "terminalIp");
            return (Criteria) this;
        }

        public Criteria andTerminalIpNotBetween(String value1, String value2) {
            addCriterion("terminal_ip not between", value1, value2, "terminalIp");
            return (Criteria) this;
        }

        public Criteria andStationIpIsNull() {
            addCriterion("station_ip is null");
            return (Criteria) this;
        }

        public Criteria andStationIpIsNotNull() {
            addCriterion("station_ip is not null");
            return (Criteria) this;
        }

        public Criteria andStationIpEqualTo(String value) {
            addCriterion("station_ip =", value, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpNotEqualTo(String value) {
            addCriterion("station_ip <>", value, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpGreaterThan(String value) {
            addCriterion("station_ip >", value, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpGreaterThanOrEqualTo(String value) {
            addCriterion("station_ip >=", value, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpLessThan(String value) {
            addCriterion("station_ip <", value, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpLessThanOrEqualTo(String value) {
            addCriterion("station_ip <=", value, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpLike(String value) {
            addCriterion("station_ip like", value, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpNotLike(String value) {
            addCriterion("station_ip not like", value, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpIn(List<String> values) {
            addCriterion("station_ip in", values, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpNotIn(List<String> values) {
            addCriterion("station_ip not in", values, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpBetween(String value1, String value2) {
            addCriterion("station_ip between", value1, value2, "stationIp");
            return (Criteria) this;
        }

        public Criteria andStationIpNotBetween(String value1, String value2) {
            addCriterion("station_ip not between", value1, value2, "stationIp");
            return (Criteria) this;
        }

        public Criteria andTerminalRealTimeIsNull() {
            addCriterion("terminal_real_time is null");
            return (Criteria) this;
        }

        public Criteria andTerminalRealTimeIsNotNull() {
            addCriterion("terminal_real_time is not null");
            return (Criteria) this;
        }

        public Criteria andTerminalRealTimeEqualTo(Date value) {
            addCriterion("terminal_real_time =", value, "terminalRealTime");
            return (Criteria) this;
        }

        public Criteria andTerminalRealTimeNotEqualTo(Date value) {
            addCriterion("terminal_real_time <>", value, "terminalRealTime");
            return (Criteria) this;
        }

        public Criteria andTerminalRealTimeGreaterThan(Date value) {
            addCriterion("terminal_real_time >", value, "terminalRealTime");
            return (Criteria) this;
        }

        public Criteria andTerminalRealTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("terminal_real_time >=", value, "terminalRealTime");
            return (Criteria) this;
        }

        public Criteria andTerminalRealTimeLessThan(Date value) {
            addCriterion("terminal_real_time <", value, "terminalRealTime");
            return (Criteria) this;
        }

        public Criteria andTerminalRealTimeLessThanOrEqualTo(Date value) {
            addCriterion("terminal_real_time <=", value, "terminalRealTime");
            return (Criteria) this;
        }

        public Criteria andTerminalRealTimeIn(List<Date> values) {
            addCriterion("terminal_real_time in", values, "terminalRealTime");
            return (Criteria) this;
        }

        public Criteria andTerminalRealTimeNotIn(List<Date> values) {
            addCriterion("terminal_real_time not in", values, "terminalRealTime");
            return (Criteria) this;
        }

        public Criteria andTerminalRealTimeBetween(Date value1, Date value2) {
            addCriterion("terminal_real_time between", value1, value2, "terminalRealTime");
            return (Criteria) this;
        }

        public Criteria andTerminalRealTimeNotBetween(Date value1, Date value2) {
            addCriterion("terminal_real_time not between", value1, value2, "terminalRealTime");
            return (Criteria) this;
        }

        public Criteria andInfoTypeIsNull() {
            addCriterion("info_type is null");
            return (Criteria) this;
        }

        public Criteria andInfoTypeIsNotNull() {
            addCriterion("info_type is not null");
            return (Criteria) this;
        }

        public Criteria andInfoTypeEqualTo(Boolean value) {
            addCriterion("info_type =", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeNotEqualTo(Boolean value) {
            addCriterion("info_type <>", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeGreaterThan(Boolean value) {
            addCriterion("info_type >", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("info_type >=", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeLessThan(Boolean value) {
            addCriterion("info_type <", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("info_type <=", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeIn(List<Boolean> values) {
            addCriterion("info_type in", values, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeNotIn(List<Boolean> values) {
            addCriterion("info_type not in", values, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("info_type between", value1, value2, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("info_type not between", value1, value2, "infoType");
            return (Criteria) this;
        }

        public Criteria andSequenceIdIsNull() {
            addCriterion("sequence_id is null");
            return (Criteria) this;
        }

        public Criteria andSequenceIdIsNotNull() {
            addCriterion("sequence_id is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceIdEqualTo(Integer value) {
            addCriterion("sequence_id =", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdNotEqualTo(Integer value) {
            addCriterion("sequence_id <>", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdGreaterThan(Integer value) {
            addCriterion("sequence_id >", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sequence_id >=", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdLessThan(Integer value) {
            addCriterion("sequence_id <", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdLessThanOrEqualTo(Integer value) {
            addCriterion("sequence_id <=", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdIn(List<Integer> values) {
            addCriterion("sequence_id in", values, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdNotIn(List<Integer> values) {
            addCriterion("sequence_id not in", values, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdBetween(Integer value1, Integer value2) {
            addCriterion("sequence_id between", value1, value2, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sequence_id not between", value1, value2, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andPositionIdIsNull() {
            addCriterion("position_id is null");
            return (Criteria) this;
        }

        public Criteria andPositionIdIsNotNull() {
            addCriterion("position_id is not null");
            return (Criteria) this;
        }

        public Criteria andPositionIdEqualTo(Integer value) {
            addCriterion("position_id =", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotEqualTo(Integer value) {
            addCriterion("position_id <>", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdGreaterThan(Integer value) {
            addCriterion("position_id >", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("position_id >=", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdLessThan(Integer value) {
            addCriterion("position_id <", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdLessThanOrEqualTo(Integer value) {
            addCriterion("position_id <=", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdIn(List<Integer> values) {
            addCriterion("position_id in", values, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotIn(List<Integer> values) {
            addCriterion("position_id not in", values, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdBetween(Integer value1, Integer value2) {
            addCriterion("position_id between", value1, value2, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("position_id not between", value1, value2, "positionId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rt_gas_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}