package com.zkxh.demo.model.rt_gas;

import java.util.Date;

public class RtGasInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.rt_gas_info_id
     *
     * @mbg.generated
     */
    private Integer rtGasInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.co
     *
     * @mbg.generated
     */
    private Double co;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.co_unit
     *
     * @mbg.generated
     */
    private Integer coUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.ch4
     *
     * @mbg.generated
     */
    private Double ch4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.ch4_unit
     *
     * @mbg.generated
     */
    private Integer ch4Unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.o2
     *
     * @mbg.generated
     */
    private Double o2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.o2_unit
     *
     * @mbg.generated
     */
    private Integer o2Unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.co2
     *
     * @mbg.generated
     */
    private Double co2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.co2_unit
     *
     * @mbg.generated
     */
    private Integer co2Unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.temperature
     *
     * @mbg.generated
     */
    private Double temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.temperature_unit
     *
     * @mbg.generated
     */
    private Integer temperatureUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.humidity
     *
     * @mbg.generated
     */
    private Double humidity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.humidity_unit
     *
     * @mbg.generated
     */
    private Integer humidityUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.field_3
     *
     * @mbg.generated
     */
    private Double field3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.field_3_unit
     *
     * @mbg.generated
     */
    private Integer field3Unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.terminal_id
     *
     * @mbg.generated
     */
    private Integer terminalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.station_id
     *
     * @mbg.generated
     */
    private Integer stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.terminal_ip
     *
     * @mbg.generated
     */
    private String terminalIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.station_ip
     *
     * @mbg.generated
     */
    private String stationIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.terminal_real_time
     *
     * @mbg.generated
     */
    private Date terminalRealTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.info_type
     *
     * @mbg.generated
     */
    private Boolean infoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.sequence_id
     *
     * @mbg.generated
     */
    private Integer sequenceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rt_gas_info.position_id
     *
     * @mbg.generated
     */
    private Integer positionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.rt_gas_info_id
     *
     * @return the value of rt_gas_info.rt_gas_info_id
     *
     * @mbg.generated
     */
    public Integer getRtGasInfoId() {
        return rtGasInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.rt_gas_info_id
     *
     * @param rtGasInfoId the value for rt_gas_info.rt_gas_info_id
     *
     * @mbg.generated
     */
    public void setRtGasInfoId(Integer rtGasInfoId) {
        this.rtGasInfoId = rtGasInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.co
     *
     * @return the value of rt_gas_info.co
     *
     * @mbg.generated
     */
    public Double getCo() {
        return co;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.co
     *
     * @param co the value for rt_gas_info.co
     *
     * @mbg.generated
     */
    public void setCo(Double co) {
        this.co = co;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.co_unit
     *
     * @return the value of rt_gas_info.co_unit
     *
     * @mbg.generated
     */
    public Integer getCoUnit() {
        return coUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.co_unit
     *
     * @param coUnit the value for rt_gas_info.co_unit
     *
     * @mbg.generated
     */
    public void setCoUnit(Integer coUnit) {
        this.coUnit = coUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.ch4
     *
     * @return the value of rt_gas_info.ch4
     *
     * @mbg.generated
     */
    public Double getCh4() {
        return ch4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.ch4
     *
     * @param ch4 the value for rt_gas_info.ch4
     *
     * @mbg.generated
     */
    public void setCh4(Double ch4) {
        this.ch4 = ch4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.ch4_unit
     *
     * @return the value of rt_gas_info.ch4_unit
     *
     * @mbg.generated
     */
    public Integer getCh4Unit() {
        return ch4Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.ch4_unit
     *
     * @param ch4Unit the value for rt_gas_info.ch4_unit
     *
     * @mbg.generated
     */
    public void setCh4Unit(Integer ch4Unit) {
        this.ch4Unit = ch4Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.o2
     *
     * @return the value of rt_gas_info.o2
     *
     * @mbg.generated
     */
    public Double getO2() {
        return o2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.o2
     *
     * @param o2 the value for rt_gas_info.o2
     *
     * @mbg.generated
     */
    public void setO2(Double o2) {
        this.o2 = o2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.o2_unit
     *
     * @return the value of rt_gas_info.o2_unit
     *
     * @mbg.generated
     */
    public Integer getO2Unit() {
        return o2Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.o2_unit
     *
     * @param o2Unit the value for rt_gas_info.o2_unit
     *
     * @mbg.generated
     */
    public void setO2Unit(Integer o2Unit) {
        this.o2Unit = o2Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.co2
     *
     * @return the value of rt_gas_info.co2
     *
     * @mbg.generated
     */
    public Double getCo2() {
        return co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.co2
     *
     * @param co2 the value for rt_gas_info.co2
     *
     * @mbg.generated
     */
    public void setCo2(Double co2) {
        this.co2 = co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.co2_unit
     *
     * @return the value of rt_gas_info.co2_unit
     *
     * @mbg.generated
     */
    public Integer getCo2Unit() {
        return co2Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.co2_unit
     *
     * @param co2Unit the value for rt_gas_info.co2_unit
     *
     * @mbg.generated
     */
    public void setCo2Unit(Integer co2Unit) {
        this.co2Unit = co2Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.temperature
     *
     * @return the value of rt_gas_info.temperature
     *
     * @mbg.generated
     */
    public Double getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.temperature
     *
     * @param temperature the value for rt_gas_info.temperature
     *
     * @mbg.generated
     */
    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.temperature_unit
     *
     * @return the value of rt_gas_info.temperature_unit
     *
     * @mbg.generated
     */
    public Integer getTemperatureUnit() {
        return temperatureUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.temperature_unit
     *
     * @param temperatureUnit the value for rt_gas_info.temperature_unit
     *
     * @mbg.generated
     */
    public void setTemperatureUnit(Integer temperatureUnit) {
        this.temperatureUnit = temperatureUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.humidity
     *
     * @return the value of rt_gas_info.humidity
     *
     * @mbg.generated
     */
    public Double getHumidity() {
        return humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.humidity
     *
     * @param humidity the value for rt_gas_info.humidity
     *
     * @mbg.generated
     */
    public void setHumidity(Double humidity) {
        this.humidity = humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.humidity_unit
     *
     * @return the value of rt_gas_info.humidity_unit
     *
     * @mbg.generated
     */
    public Integer getHumidityUnit() {
        return humidityUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.humidity_unit
     *
     * @param humidityUnit the value for rt_gas_info.humidity_unit
     *
     * @mbg.generated
     */
    public void setHumidityUnit(Integer humidityUnit) {
        this.humidityUnit = humidityUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.field_3
     *
     * @return the value of rt_gas_info.field_3
     *
     * @mbg.generated
     */
    public Double getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.field_3
     *
     * @param field3 the value for rt_gas_info.field_3
     *
     * @mbg.generated
     */
    public void setField3(Double field3) {
        this.field3 = field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.field_3_unit
     *
     * @return the value of rt_gas_info.field_3_unit
     *
     * @mbg.generated
     */
    public Integer getField3Unit() {
        return field3Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.field_3_unit
     *
     * @param field3Unit the value for rt_gas_info.field_3_unit
     *
     * @mbg.generated
     */
    public void setField3Unit(Integer field3Unit) {
        this.field3Unit = field3Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.create_time
     *
     * @return the value of rt_gas_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.create_time
     *
     * @param createTime the value for rt_gas_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.terminal_id
     *
     * @return the value of rt_gas_info.terminal_id
     *
     * @mbg.generated
     */
    public Integer getTerminalId() {
        return terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.terminal_id
     *
     * @param terminalId the value for rt_gas_info.terminal_id
     *
     * @mbg.generated
     */
    public void setTerminalId(Integer terminalId) {
        this.terminalId = terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.station_id
     *
     * @return the value of rt_gas_info.station_id
     *
     * @mbg.generated
     */
    public Integer getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.station_id
     *
     * @param stationId the value for rt_gas_info.station_id
     *
     * @mbg.generated
     */
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.terminal_ip
     *
     * @return the value of rt_gas_info.terminal_ip
     *
     * @mbg.generated
     */
    public String getTerminalIp() {
        return terminalIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.terminal_ip
     *
     * @param terminalIp the value for rt_gas_info.terminal_ip
     *
     * @mbg.generated
     */
    public void setTerminalIp(String terminalIp) {
        this.terminalIp = terminalIp == null ? null : terminalIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.station_ip
     *
     * @return the value of rt_gas_info.station_ip
     *
     * @mbg.generated
     */
    public String getStationIp() {
        return stationIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.station_ip
     *
     * @param stationIp the value for rt_gas_info.station_ip
     *
     * @mbg.generated
     */
    public void setStationIp(String stationIp) {
        this.stationIp = stationIp == null ? null : stationIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.terminal_real_time
     *
     * @return the value of rt_gas_info.terminal_real_time
     *
     * @mbg.generated
     */
    public Date getTerminalRealTime() {
        return terminalRealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.terminal_real_time
     *
     * @param terminalRealTime the value for rt_gas_info.terminal_real_time
     *
     * @mbg.generated
     */
    public void setTerminalRealTime(Date terminalRealTime) {
        this.terminalRealTime = terminalRealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.info_type
     *
     * @return the value of rt_gas_info.info_type
     *
     * @mbg.generated
     */
    public Boolean getInfoType() {
        return infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.info_type
     *
     * @param infoType the value for rt_gas_info.info_type
     *
     * @mbg.generated
     */
    public void setInfoType(Boolean infoType) {
        this.infoType = infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.sequence_id
     *
     * @return the value of rt_gas_info.sequence_id
     *
     * @mbg.generated
     */
    public Integer getSequenceId() {
        return sequenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.sequence_id
     *
     * @param sequenceId the value for rt_gas_info.sequence_id
     *
     * @mbg.generated
     */
    public void setSequenceId(Integer sequenceId) {
        this.sequenceId = sequenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rt_gas_info.position_id
     *
     * @return the value of rt_gas_info.position_id
     *
     * @mbg.generated
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rt_gas_info.position_id
     *
     * @param positionId the value for rt_gas_info.position_id
     *
     * @mbg.generated
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }
}