package com.zkxh.demo.model.user;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    public SysUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSysUseridIsNull() {
            addCriterion("sys_userid is null");
            return (Criteria) this;
        }

        public Criteria andSysUseridIsNotNull() {
            addCriterion("sys_userid is not null");
            return (Criteria) this;
        }

        public Criteria andSysUseridEqualTo(Integer value) {
            addCriterion("sys_userid =", value, "sysUserid");
            return (Criteria) this;
        }

        public Criteria andSysUseridNotEqualTo(Integer value) {
            addCriterion("sys_userid <>", value, "sysUserid");
            return (Criteria) this;
        }

        public Criteria andSysUseridGreaterThan(Integer value) {
            addCriterion("sys_userid >", value, "sysUserid");
            return (Criteria) this;
        }

        public Criteria andSysUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("sys_userid >=", value, "sysUserid");
            return (Criteria) this;
        }

        public Criteria andSysUseridLessThan(Integer value) {
            addCriterion("sys_userid <", value, "sysUserid");
            return (Criteria) this;
        }

        public Criteria andSysUseridLessThanOrEqualTo(Integer value) {
            addCriterion("sys_userid <=", value, "sysUserid");
            return (Criteria) this;
        }

        public Criteria andSysUseridIn(List<Integer> values) {
            addCriterion("sys_userid in", values, "sysUserid");
            return (Criteria) this;
        }

        public Criteria andSysUseridNotIn(List<Integer> values) {
            addCriterion("sys_userid not in", values, "sysUserid");
            return (Criteria) this;
        }

        public Criteria andSysUseridBetween(Integer value1, Integer value2) {
            addCriterion("sys_userid between", value1, value2, "sysUserid");
            return (Criteria) this;
        }

        public Criteria andSysUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("sys_userid not between", value1, value2, "sysUserid");
            return (Criteria) this;
        }

        public Criteria andSysUsernameIsNull() {
            addCriterion("sys_username is null");
            return (Criteria) this;
        }

        public Criteria andSysUsernameIsNotNull() {
            addCriterion("sys_username is not null");
            return (Criteria) this;
        }

        public Criteria andSysUsernameEqualTo(String value) {
            addCriterion("sys_username =", value, "sysUsername");
            return (Criteria) this;
        }

        public Criteria andSysUsernameNotEqualTo(String value) {
            addCriterion("sys_username <>", value, "sysUsername");
            return (Criteria) this;
        }

        public Criteria andSysUsernameGreaterThan(String value) {
            addCriterion("sys_username >", value, "sysUsername");
            return (Criteria) this;
        }

        public Criteria andSysUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("sys_username >=", value, "sysUsername");
            return (Criteria) this;
        }

        public Criteria andSysUsernameLessThan(String value) {
            addCriterion("sys_username <", value, "sysUsername");
            return (Criteria) this;
        }

        public Criteria andSysUsernameLessThanOrEqualTo(String value) {
            addCriterion("sys_username <=", value, "sysUsername");
            return (Criteria) this;
        }

        public Criteria andSysUsernameLike(String value) {
            addCriterion("sys_username like", value, "sysUsername");
            return (Criteria) this;
        }

        public Criteria andSysUsernameNotLike(String value) {
            addCriterion("sys_username not like", value, "sysUsername");
            return (Criteria) this;
        }

        public Criteria andSysUsernameIn(List<String> values) {
            addCriterion("sys_username in", values, "sysUsername");
            return (Criteria) this;
        }

        public Criteria andSysUsernameNotIn(List<String> values) {
            addCriterion("sys_username not in", values, "sysUsername");
            return (Criteria) this;
        }

        public Criteria andSysUsernameBetween(String value1, String value2) {
            addCriterion("sys_username between", value1, value2, "sysUsername");
            return (Criteria) this;
        }

        public Criteria andSysUsernameNotBetween(String value1, String value2) {
            addCriterion("sys_username not between", value1, value2, "sysUsername");
            return (Criteria) this;
        }

        public Criteria andSysAccountIsNull() {
            addCriterion("sys_account is null");
            return (Criteria) this;
        }

        public Criteria andSysAccountIsNotNull() {
            addCriterion("sys_account is not null");
            return (Criteria) this;
        }

        public Criteria andSysAccountEqualTo(String value) {
            addCriterion("sys_account =", value, "sysAccount");
            return (Criteria) this;
        }

        public Criteria andSysAccountNotEqualTo(String value) {
            addCriterion("sys_account <>", value, "sysAccount");
            return (Criteria) this;
        }

        public Criteria andSysAccountGreaterThan(String value) {
            addCriterion("sys_account >", value, "sysAccount");
            return (Criteria) this;
        }

        public Criteria andSysAccountGreaterThanOrEqualTo(String value) {
            addCriterion("sys_account >=", value, "sysAccount");
            return (Criteria) this;
        }

        public Criteria andSysAccountLessThan(String value) {
            addCriterion("sys_account <", value, "sysAccount");
            return (Criteria) this;
        }

        public Criteria andSysAccountLessThanOrEqualTo(String value) {
            addCriterion("sys_account <=", value, "sysAccount");
            return (Criteria) this;
        }

        public Criteria andSysAccountLike(String value) {
            addCriterion("sys_account like", value, "sysAccount");
            return (Criteria) this;
        }

        public Criteria andSysAccountNotLike(String value) {
            addCriterion("sys_account not like", value, "sysAccount");
            return (Criteria) this;
        }

        public Criteria andSysAccountIn(List<String> values) {
            addCriterion("sys_account in", values, "sysAccount");
            return (Criteria) this;
        }

        public Criteria andSysAccountNotIn(List<String> values) {
            addCriterion("sys_account not in", values, "sysAccount");
            return (Criteria) this;
        }

        public Criteria andSysAccountBetween(String value1, String value2) {
            addCriterion("sys_account between", value1, value2, "sysAccount");
            return (Criteria) this;
        }

        public Criteria andSysAccountNotBetween(String value1, String value2) {
            addCriterion("sys_account not between", value1, value2, "sysAccount");
            return (Criteria) this;
        }

        public Criteria andSysPasswordIsNull() {
            addCriterion("sys_password is null");
            return (Criteria) this;
        }

        public Criteria andSysPasswordIsNotNull() {
            addCriterion("sys_password is not null");
            return (Criteria) this;
        }

        public Criteria andSysPasswordEqualTo(String value) {
            addCriterion("sys_password =", value, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordNotEqualTo(String value) {
            addCriterion("sys_password <>", value, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordGreaterThan(String value) {
            addCriterion("sys_password >", value, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("sys_password >=", value, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordLessThan(String value) {
            addCriterion("sys_password <", value, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordLessThanOrEqualTo(String value) {
            addCriterion("sys_password <=", value, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordLike(String value) {
            addCriterion("sys_password like", value, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordNotLike(String value) {
            addCriterion("sys_password not like", value, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordIn(List<String> values) {
            addCriterion("sys_password in", values, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordNotIn(List<String> values) {
            addCriterion("sys_password not in", values, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordBetween(String value1, String value2) {
            addCriterion("sys_password between", value1, value2, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordNotBetween(String value1, String value2) {
            addCriterion("sys_password not between", value1, value2, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysNicknameIsNull() {
            addCriterion("sys_nickname is null");
            return (Criteria) this;
        }

        public Criteria andSysNicknameIsNotNull() {
            addCriterion("sys_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andSysNicknameEqualTo(String value) {
            addCriterion("sys_nickname =", value, "sysNickname");
            return (Criteria) this;
        }

        public Criteria andSysNicknameNotEqualTo(String value) {
            addCriterion("sys_nickname <>", value, "sysNickname");
            return (Criteria) this;
        }

        public Criteria andSysNicknameGreaterThan(String value) {
            addCriterion("sys_nickname >", value, "sysNickname");
            return (Criteria) this;
        }

        public Criteria andSysNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("sys_nickname >=", value, "sysNickname");
            return (Criteria) this;
        }

        public Criteria andSysNicknameLessThan(String value) {
            addCriterion("sys_nickname <", value, "sysNickname");
            return (Criteria) this;
        }

        public Criteria andSysNicknameLessThanOrEqualTo(String value) {
            addCriterion("sys_nickname <=", value, "sysNickname");
            return (Criteria) this;
        }

        public Criteria andSysNicknameLike(String value) {
            addCriterion("sys_nickname like", value, "sysNickname");
            return (Criteria) this;
        }

        public Criteria andSysNicknameNotLike(String value) {
            addCriterion("sys_nickname not like", value, "sysNickname");
            return (Criteria) this;
        }

        public Criteria andSysNicknameIn(List<String> values) {
            addCriterion("sys_nickname in", values, "sysNickname");
            return (Criteria) this;
        }

        public Criteria andSysNicknameNotIn(List<String> values) {
            addCriterion("sys_nickname not in", values, "sysNickname");
            return (Criteria) this;
        }

        public Criteria andSysNicknameBetween(String value1, String value2) {
            addCriterion("sys_nickname between", value1, value2, "sysNickname");
            return (Criteria) this;
        }

        public Criteria andSysNicknameNotBetween(String value1, String value2) {
            addCriterion("sys_nickname not between", value1, value2, "sysNickname");
            return (Criteria) this;
        }

        public Criteria andSysHeadimgIsNull() {
            addCriterion("sys_headimg is null");
            return (Criteria) this;
        }

        public Criteria andSysHeadimgIsNotNull() {
            addCriterion("sys_headimg is not null");
            return (Criteria) this;
        }

        public Criteria andSysHeadimgEqualTo(String value) {
            addCriterion("sys_headimg =", value, "sysHeadimg");
            return (Criteria) this;
        }

        public Criteria andSysHeadimgNotEqualTo(String value) {
            addCriterion("sys_headimg <>", value, "sysHeadimg");
            return (Criteria) this;
        }

        public Criteria andSysHeadimgGreaterThan(String value) {
            addCriterion("sys_headimg >", value, "sysHeadimg");
            return (Criteria) this;
        }

        public Criteria andSysHeadimgGreaterThanOrEqualTo(String value) {
            addCriterion("sys_headimg >=", value, "sysHeadimg");
            return (Criteria) this;
        }

        public Criteria andSysHeadimgLessThan(String value) {
            addCriterion("sys_headimg <", value, "sysHeadimg");
            return (Criteria) this;
        }

        public Criteria andSysHeadimgLessThanOrEqualTo(String value) {
            addCriterion("sys_headimg <=", value, "sysHeadimg");
            return (Criteria) this;
        }

        public Criteria andSysHeadimgLike(String value) {
            addCriterion("sys_headimg like", value, "sysHeadimg");
            return (Criteria) this;
        }

        public Criteria andSysHeadimgNotLike(String value) {
            addCriterion("sys_headimg not like", value, "sysHeadimg");
            return (Criteria) this;
        }

        public Criteria andSysHeadimgIn(List<String> values) {
            addCriterion("sys_headimg in", values, "sysHeadimg");
            return (Criteria) this;
        }

        public Criteria andSysHeadimgNotIn(List<String> values) {
            addCriterion("sys_headimg not in", values, "sysHeadimg");
            return (Criteria) this;
        }

        public Criteria andSysHeadimgBetween(String value1, String value2) {
            addCriterion("sys_headimg between", value1, value2, "sysHeadimg");
            return (Criteria) this;
        }

        public Criteria andSysHeadimgNotBetween(String value1, String value2) {
            addCriterion("sys_headimg not between", value1, value2, "sysHeadimg");
            return (Criteria) this;
        }

        public Criteria andSysRegisterTimeIsNull() {
            addCriterion("sys_register_time is null");
            return (Criteria) this;
        }

        public Criteria andSysRegisterTimeIsNotNull() {
            addCriterion("sys_register_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysRegisterTimeEqualTo(Date value) {
            addCriterion("sys_register_time =", value, "sysRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisterTimeNotEqualTo(Date value) {
            addCriterion("sys_register_time <>", value, "sysRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisterTimeGreaterThan(Date value) {
            addCriterion("sys_register_time >", value, "sysRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisterTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sys_register_time >=", value, "sysRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisterTimeLessThan(Date value) {
            addCriterion("sys_register_time <", value, "sysRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisterTimeLessThanOrEqualTo(Date value) {
            addCriterion("sys_register_time <=", value, "sysRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisterTimeIn(List<Date> values) {
            addCriterion("sys_register_time in", values, "sysRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisterTimeNotIn(List<Date> values) {
            addCriterion("sys_register_time not in", values, "sysRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisterTimeBetween(Date value1, Date value2) {
            addCriterion("sys_register_time between", value1, value2, "sysRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisterTimeNotBetween(Date value1, Date value2) {
            addCriterion("sys_register_time not between", value1, value2, "sysRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSysLastModifyTimeIsNull() {
            addCriterion("sys_last_modify_time is null");
            return (Criteria) this;
        }

        public Criteria andSysLastModifyTimeIsNotNull() {
            addCriterion("sys_last_modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysLastModifyTimeEqualTo(Date value) {
            addCriterion("sys_last_modify_time =", value, "sysLastModifyTime");
            return (Criteria) this;
        }

        public Criteria andSysLastModifyTimeNotEqualTo(Date value) {
            addCriterion("sys_last_modify_time <>", value, "sysLastModifyTime");
            return (Criteria) this;
        }

        public Criteria andSysLastModifyTimeGreaterThan(Date value) {
            addCriterion("sys_last_modify_time >", value, "sysLastModifyTime");
            return (Criteria) this;
        }

        public Criteria andSysLastModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sys_last_modify_time >=", value, "sysLastModifyTime");
            return (Criteria) this;
        }

        public Criteria andSysLastModifyTimeLessThan(Date value) {
            addCriterion("sys_last_modify_time <", value, "sysLastModifyTime");
            return (Criteria) this;
        }

        public Criteria andSysLastModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("sys_last_modify_time <=", value, "sysLastModifyTime");
            return (Criteria) this;
        }

        public Criteria andSysLastModifyTimeIn(List<Date> values) {
            addCriterion("sys_last_modify_time in", values, "sysLastModifyTime");
            return (Criteria) this;
        }

        public Criteria andSysLastModifyTimeNotIn(List<Date> values) {
            addCriterion("sys_last_modify_time not in", values, "sysLastModifyTime");
            return (Criteria) this;
        }

        public Criteria andSysLastModifyTimeBetween(Date value1, Date value2) {
            addCriterion("sys_last_modify_time between", value1, value2, "sysLastModifyTime");
            return (Criteria) this;
        }

        public Criteria andSysLastModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("sys_last_modify_time not between", value1, value2, "sysLastModifyTime");
            return (Criteria) this;
        }

        public Criteria andSysPhonenumberIsNull() {
            addCriterion("sys_phonenumber is null");
            return (Criteria) this;
        }

        public Criteria andSysPhonenumberIsNotNull() {
            addCriterion("sys_phonenumber is not null");
            return (Criteria) this;
        }

        public Criteria andSysPhonenumberEqualTo(String value) {
            addCriterion("sys_phonenumber =", value, "sysPhonenumber");
            return (Criteria) this;
        }

        public Criteria andSysPhonenumberNotEqualTo(String value) {
            addCriterion("sys_phonenumber <>", value, "sysPhonenumber");
            return (Criteria) this;
        }

        public Criteria andSysPhonenumberGreaterThan(String value) {
            addCriterion("sys_phonenumber >", value, "sysPhonenumber");
            return (Criteria) this;
        }

        public Criteria andSysPhonenumberGreaterThanOrEqualTo(String value) {
            addCriterion("sys_phonenumber >=", value, "sysPhonenumber");
            return (Criteria) this;
        }

        public Criteria andSysPhonenumberLessThan(String value) {
            addCriterion("sys_phonenumber <", value, "sysPhonenumber");
            return (Criteria) this;
        }

        public Criteria andSysPhonenumberLessThanOrEqualTo(String value) {
            addCriterion("sys_phonenumber <=", value, "sysPhonenumber");
            return (Criteria) this;
        }

        public Criteria andSysPhonenumberLike(String value) {
            addCriterion("sys_phonenumber like", value, "sysPhonenumber");
            return (Criteria) this;
        }

        public Criteria andSysPhonenumberNotLike(String value) {
            addCriterion("sys_phonenumber not like", value, "sysPhonenumber");
            return (Criteria) this;
        }

        public Criteria andSysPhonenumberIn(List<String> values) {
            addCriterion("sys_phonenumber in", values, "sysPhonenumber");
            return (Criteria) this;
        }

        public Criteria andSysPhonenumberNotIn(List<String> values) {
            addCriterion("sys_phonenumber not in", values, "sysPhonenumber");
            return (Criteria) this;
        }

        public Criteria andSysPhonenumberBetween(String value1, String value2) {
            addCriterion("sys_phonenumber between", value1, value2, "sysPhonenumber");
            return (Criteria) this;
        }

        public Criteria andSysPhonenumberNotBetween(String value1, String value2) {
            addCriterion("sys_phonenumber not between", value1, value2, "sysPhonenumber");
            return (Criteria) this;
        }

        public Criteria andSysLastLoginTimeIsNull() {
            addCriterion("sys_last_login_time is null");
            return (Criteria) this;
        }

        public Criteria andSysLastLoginTimeIsNotNull() {
            addCriterion("sys_last_login_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysLastLoginTimeEqualTo(Date value) {
            addCriterion("sys_last_login_time =", value, "sysLastLoginTime");
            return (Criteria) this;
        }

        public Criteria andSysLastLoginTimeNotEqualTo(Date value) {
            addCriterion("sys_last_login_time <>", value, "sysLastLoginTime");
            return (Criteria) this;
        }

        public Criteria andSysLastLoginTimeGreaterThan(Date value) {
            addCriterion("sys_last_login_time >", value, "sysLastLoginTime");
            return (Criteria) this;
        }

        public Criteria andSysLastLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sys_last_login_time >=", value, "sysLastLoginTime");
            return (Criteria) this;
        }

        public Criteria andSysLastLoginTimeLessThan(Date value) {
            addCriterion("sys_last_login_time <", value, "sysLastLoginTime");
            return (Criteria) this;
        }

        public Criteria andSysLastLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("sys_last_login_time <=", value, "sysLastLoginTime");
            return (Criteria) this;
        }

        public Criteria andSysLastLoginTimeIn(List<Date> values) {
            addCriterion("sys_last_login_time in", values, "sysLastLoginTime");
            return (Criteria) this;
        }

        public Criteria andSysLastLoginTimeNotIn(List<Date> values) {
            addCriterion("sys_last_login_time not in", values, "sysLastLoginTime");
            return (Criteria) this;
        }

        public Criteria andSysLastLoginTimeBetween(Date value1, Date value2) {
            addCriterion("sys_last_login_time between", value1, value2, "sysLastLoginTime");
            return (Criteria) this;
        }

        public Criteria andSysLastLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("sys_last_login_time not between", value1, value2, "sysLastLoginTime");
            return (Criteria) this;
        }

        public Criteria andUserGroupIdIsNull() {
            addCriterion("user_group_id is null");
            return (Criteria) this;
        }

        public Criteria andUserGroupIdIsNotNull() {
            addCriterion("user_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserGroupIdEqualTo(Integer value) {
            addCriterion("user_group_id =", value, "userGroupId");
            return (Criteria) this;
        }

        public Criteria andUserGroupIdNotEqualTo(Integer value) {
            addCriterion("user_group_id <>", value, "userGroupId");
            return (Criteria) this;
        }

        public Criteria andUserGroupIdGreaterThan(Integer value) {
            addCriterion("user_group_id >", value, "userGroupId");
            return (Criteria) this;
        }

        public Criteria andUserGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_group_id >=", value, "userGroupId");
            return (Criteria) this;
        }

        public Criteria andUserGroupIdLessThan(Integer value) {
            addCriterion("user_group_id <", value, "userGroupId");
            return (Criteria) this;
        }

        public Criteria andUserGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_group_id <=", value, "userGroupId");
            return (Criteria) this;
        }

        public Criteria andUserGroupIdIn(List<Integer> values) {
            addCriterion("user_group_id in", values, "userGroupId");
            return (Criteria) this;
        }

        public Criteria andUserGroupIdNotIn(List<Integer> values) {
            addCriterion("user_group_id not in", values, "userGroupId");
            return (Criteria) this;
        }

        public Criteria andUserGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("user_group_id between", value1, value2, "userGroupId");
            return (Criteria) this;
        }

        public Criteria andUserGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_group_id not between", value1, value2, "userGroupId");
            return (Criteria) this;
        }

        public Criteria andSysUserLevelIsNull() {
            addCriterion("sys_user_level is null");
            return (Criteria) this;
        }

        public Criteria andSysUserLevelIsNotNull() {
            addCriterion("sys_user_level is not null");
            return (Criteria) this;
        }

        public Criteria andSysUserLevelEqualTo(String value) {
            addCriterion("sys_user_level =", value, "sysUserLevel");
            return (Criteria) this;
        }

        public Criteria andSysUserLevelNotEqualTo(String value) {
            addCriterion("sys_user_level <>", value, "sysUserLevel");
            return (Criteria) this;
        }

        public Criteria andSysUserLevelGreaterThan(String value) {
            addCriterion("sys_user_level >", value, "sysUserLevel");
            return (Criteria) this;
        }

        public Criteria andSysUserLevelGreaterThanOrEqualTo(String value) {
            addCriterion("sys_user_level >=", value, "sysUserLevel");
            return (Criteria) this;
        }

        public Criteria andSysUserLevelLessThan(String value) {
            addCriterion("sys_user_level <", value, "sysUserLevel");
            return (Criteria) this;
        }

        public Criteria andSysUserLevelLessThanOrEqualTo(String value) {
            addCriterion("sys_user_level <=", value, "sysUserLevel");
            return (Criteria) this;
        }

        public Criteria andSysUserLevelLike(String value) {
            addCriterion("sys_user_level like", value, "sysUserLevel");
            return (Criteria) this;
        }

        public Criteria andSysUserLevelNotLike(String value) {
            addCriterion("sys_user_level not like", value, "sysUserLevel");
            return (Criteria) this;
        }

        public Criteria andSysUserLevelIn(List<String> values) {
            addCriterion("sys_user_level in", values, "sysUserLevel");
            return (Criteria) this;
        }

        public Criteria andSysUserLevelNotIn(List<String> values) {
            addCriterion("sys_user_level not in", values, "sysUserLevel");
            return (Criteria) this;
        }

        public Criteria andSysUserLevelBetween(String value1, String value2) {
            addCriterion("sys_user_level between", value1, value2, "sysUserLevel");
            return (Criteria) this;
        }

        public Criteria andSysUserLevelNotBetween(String value1, String value2) {
            addCriterion("sys_user_level not between", value1, value2, "sysUserLevel");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("enabled is null");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("enabled is not null");
            return (Criteria) this;
        }

        public Criteria andEnabledEqualTo(Boolean value) {
            addCriterion("enabled =", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotEqualTo(Boolean value) {
            addCriterion("enabled <>", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThan(Boolean value) {
            addCriterion("enabled >", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("enabled >=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThan(Boolean value) {
            addCriterion("enabled <", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThanOrEqualTo(Boolean value) {
            addCriterion("enabled <=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledIn(List<Boolean> values) {
            addCriterion("enabled in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotIn(List<Boolean> values) {
            addCriterion("enabled not in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledBetween(Boolean value1, Boolean value2) {
            addCriterion("enabled between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("enabled not between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(Integer value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(Integer value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(Integer value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(Integer value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(Integer value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<Integer> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<Integer> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(Integer value1, Integer value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(Integer value1, Integer value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andUserSaltIsNull() {
            addCriterion("user_salt is null");
            return (Criteria) this;
        }

        public Criteria andUserSaltIsNotNull() {
            addCriterion("user_salt is not null");
            return (Criteria) this;
        }

        public Criteria andUserSaltEqualTo(String value) {
            addCriterion("user_salt =", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltNotEqualTo(String value) {
            addCriterion("user_salt <>", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltGreaterThan(String value) {
            addCriterion("user_salt >", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltGreaterThanOrEqualTo(String value) {
            addCriterion("user_salt >=", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltLessThan(String value) {
            addCriterion("user_salt <", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltLessThanOrEqualTo(String value) {
            addCriterion("user_salt <=", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltLike(String value) {
            addCriterion("user_salt like", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltNotLike(String value) {
            addCriterion("user_salt not like", value, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltIn(List<String> values) {
            addCriterion("user_salt in", values, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltNotIn(List<String> values) {
            addCriterion("user_salt not in", values, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltBetween(String value1, String value2) {
            addCriterion("user_salt between", value1, value2, "userSalt");
            return (Criteria) this;
        }

        public Criteria andUserSaltNotBetween(String value1, String value2) {
            addCriterion("user_salt not between", value1, value2, "userSalt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}