package com.zkxh.demo.model.base_station;

import java.util.Date;

public class BaseStation {

    //后补
    private Integer areaId;

    public Integer getAreaId() {
        return areaId;
    }

    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.base_station_id
     *
     * @mbg.generated
     */
    private Integer baseStationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.base_station_num
     *
     * @mbg.generated
     */
    private Integer baseStationNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.base_station_ip
     *
     * @mbg.generated
     */
    private String baseStationIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.software_version
     *
     * @mbg.generated
     */
    private String softwareVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.hardware_version
     *
     * @mbg.generated
     */
    private String hardwareVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.power_supply
     *
     * @mbg.generated
     */
    private String powerSupply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.position_x
     *
     * @mbg.generated
     */
    private Double positionX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.position_y
     *
     * @mbg.generated
     */
    private Double positionY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.position_z
     *
     * @mbg.generated
     */
    private Double positionZ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.channel
     *
     * @mbg.generated
     */
    private Integer channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.emissive_power
     *
     * @mbg.generated
     */
    private Integer emissivePower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.antenna_gain
     *
     * @mbg.generated
     */
    private Integer antennaGain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.encryption
     *
     * @mbg.generated
     */
    private Integer encryption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.SSID
     *
     * @mbg.generated
     */
    private String ssid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.subnet_mask
     *
     * @mbg.generated
     */
    private String subnetMask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_station.zone_id
     *
     * @mbg.generated
     */
    private Integer zoneId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.base_station_id
     *
     * @return the value of base_station.base_station_id
     *
     * @mbg.generated
     */
    public Integer getBaseStationId() {
        return baseStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.base_station_id
     *
     * @param baseStationId the value for base_station.base_station_id
     *
     * @mbg.generated
     */
    public void setBaseStationId(Integer baseStationId) {
        this.baseStationId = baseStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.base_station_num
     *
     * @return the value of base_station.base_station_num
     *
     * @mbg.generated
     */
    public Integer getBaseStationNum() {
        return baseStationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.base_station_num
     *
     * @param baseStationNum the value for base_station.base_station_num
     *
     * @mbg.generated
     */
    public void setBaseStationNum(Integer baseStationNum) {
        this.baseStationNum = baseStationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.base_station_ip
     *
     * @return the value of base_station.base_station_ip
     *
     * @mbg.generated
     */
    public String getBaseStationIp() {
        return baseStationIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.base_station_ip
     *
     * @param baseStationIp the value for base_station.base_station_ip
     *
     * @mbg.generated
     */
    public void setBaseStationIp(String baseStationIp) {
        this.baseStationIp = baseStationIp == null ? null : baseStationIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.software_version
     *
     * @return the value of base_station.software_version
     *
     * @mbg.generated
     */
    public String getSoftwareVersion() {
        return softwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.software_version
     *
     * @param softwareVersion the value for base_station.software_version
     *
     * @mbg.generated
     */
    public void setSoftwareVersion(String softwareVersion) {
        this.softwareVersion = softwareVersion == null ? null : softwareVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.hardware_version
     *
     * @return the value of base_station.hardware_version
     *
     * @mbg.generated
     */
    public String getHardwareVersion() {
        return hardwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.hardware_version
     *
     * @param hardwareVersion the value for base_station.hardware_version
     *
     * @mbg.generated
     */
    public void setHardwareVersion(String hardwareVersion) {
        this.hardwareVersion = hardwareVersion == null ? null : hardwareVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.power_supply
     *
     * @return the value of base_station.power_supply
     *
     * @mbg.generated
     */
    public String getPowerSupply() {
        return powerSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.power_supply
     *
     * @param powerSupply the value for base_station.power_supply
     *
     * @mbg.generated
     */
    public void setPowerSupply(String powerSupply) {
        this.powerSupply = powerSupply == null ? null : powerSupply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.create_time
     *
     * @return the value of base_station.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.create_time
     *
     * @param createTime the value for base_station.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.remark
     *
     * @return the value of base_station.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.remark
     *
     * @param remark the value for base_station.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.update_time
     *
     * @return the value of base_station.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.update_time
     *
     * @param updateTime the value for base_station.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.position_x
     *
     * @return the value of base_station.position_x
     *
     * @mbg.generated
     */
    public Double getPositionX() {
        return positionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.position_x
     *
     * @param positionX the value for base_station.position_x
     *
     * @mbg.generated
     */
    public void setPositionX(Double positionX) {
        this.positionX = positionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.position_y
     *
     * @return the value of base_station.position_y
     *
     * @mbg.generated
     */
    public Double getPositionY() {
        return positionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.position_y
     *
     * @param positionY the value for base_station.position_y
     *
     * @mbg.generated
     */
    public void setPositionY(Double positionY) {
        this.positionY = positionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.position_z
     *
     * @return the value of base_station.position_z
     *
     * @mbg.generated
     */
    public Double getPositionZ() {
        return positionZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.position_z
     *
     * @param positionZ the value for base_station.position_z
     *
     * @mbg.generated
     */
    public void setPositionZ(Double positionZ) {
        this.positionZ = positionZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.channel
     *
     * @return the value of base_station.channel
     *
     * @mbg.generated
     */
    public Integer getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.channel
     *
     * @param channel the value for base_station.channel
     *
     * @mbg.generated
     */
    public void setChannel(Integer channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.emissive_power
     *
     * @return the value of base_station.emissive_power
     *
     * @mbg.generated
     */
    public Integer getEmissivePower() {
        return emissivePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.emissive_power
     *
     * @param emissivePower the value for base_station.emissive_power
     *
     * @mbg.generated
     */
    public void setEmissivePower(Integer emissivePower) {
        this.emissivePower = emissivePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.antenna_gain
     *
     * @return the value of base_station.antenna_gain
     *
     * @mbg.generated
     */
    public Integer getAntennaGain() {
        return antennaGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.antenna_gain
     *
     * @param antennaGain the value for base_station.antenna_gain
     *
     * @mbg.generated
     */
    public void setAntennaGain(Integer antennaGain) {
        this.antennaGain = antennaGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.encryption
     *
     * @return the value of base_station.encryption
     *
     * @mbg.generated
     */
    public Integer getEncryption() {
        return encryption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.encryption
     *
     * @param encryption the value for base_station.encryption
     *
     * @mbg.generated
     */
    public void setEncryption(Integer encryption) {
        this.encryption = encryption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.SSID
     *
     * @return the value of base_station.SSID
     *
     * @mbg.generated
     */
    public String getSsid() {
        return ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.SSID
     *
     * @param ssid the value for base_station.SSID
     *
     * @mbg.generated
     */
    public void setSsid(String ssid) {
        this.ssid = ssid == null ? null : ssid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.status
     *
     * @return the value of base_station.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.status
     *
     * @param status the value for base_station.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.subnet_mask
     *
     * @return the value of base_station.subnet_mask
     *
     * @mbg.generated
     */
    public String getSubnetMask() {
        return subnetMask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.subnet_mask
     *
     * @param subnetMask the value for base_station.subnet_mask
     *
     * @mbg.generated
     */
    public void setSubnetMask(String subnetMask) {
        this.subnetMask = subnetMask == null ? null : subnetMask.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_station.zone_id
     *
     * @return the value of base_station.zone_id
     *
     * @mbg.generated
     */
    public Integer getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_station.zone_id
     *
     * @param zoneId the value for base_station.zone_id
     * @mbg.generated
     */
    public void setZoneId(Integer zoneId) {
        this.zoneId = zoneId;
    }
}
