package com.zkxh.demo.model.terminal;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

@ApiModel
public class StaffTerminal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.staff_terminal_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "staffTerminalId", value = "自主递增ID", required = false, hidden = true)
    private Integer staffTerminalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.staff_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "staffId", value = "员工ID", required = false, hidden = true)
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.terminal_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "terminalId", value = "终端ID编号", required = true, hidden = false)
    private Integer terminalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.create_time
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "createTime", value = "添加时间", required = false, hidden = false)
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.model_number
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "modelNumber", value = "类型 型号版本编号 ", required = true, hidden = false)
    private String modelNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.hardware_version
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "hardwareVersion", value = "硬件版本号", required = true, hidden = false)
    private String hardwareVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.software_version
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "softwareVersion", value = "软件版本号", required = true, hidden = false)
    private String softwareVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.co
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "co", value = "一氧化碳传感器标记", required = true, hidden = false)
    private Integer co;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.co_desc
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "coDesc", value = "一氧化碳传感器描述", required = false, hidden = false)
    private String coDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.o2
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "o2", value = "氧气传感器标记", required = true, hidden = false)
    private Integer o2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.o2_desc
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "o2Desc", value = "氧气传感器描述", required = false, hidden = false)
    private String o2Desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.ch4
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "ch4", value = "甲烷传感器标记", required = true, hidden = false)
    private Integer ch4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.ch4_desc
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "ch4Desc", value = "甲烷传感器描述", required = false, hidden = false)
    private String ch4Desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.voice
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "voice", value = "语音标记", required = true, hidden = false)
    private Integer voice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.voice_desc
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "voiceDesc", value = "语音描述", required = false, hidden = false)
    private String voiceDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.wifi
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "wifi", value = "wifi标记", required = true, hidden = false)
    private Integer wifi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.wifi_desc
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "wifiDesc", value = "wifi描述", required = false, hidden = false)
    private String wifiDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.battery
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "battery", value = "电源标记", required = true, hidden = false)
    private Integer battery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_terminal.battery_desc
     *
     * @mbg.generated
     */
    @ApiModelProperty(name = "batteryDesc", value = "电源描述", required = false, hidden = false)
    private String batteryDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.staff_terminal_id
     *
     * @return the value of staff_terminal.staff_terminal_id
     * @mbg.generated
     */
    public Integer getStaffTerminalId() {
        return staffTerminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.staff_terminal_id
     *
     * @param staffTerminalId the value for staff_terminal.staff_terminal_id
     * @mbg.generated
     */
    public void setStaffTerminalId(Integer staffTerminalId) {
        this.staffTerminalId = staffTerminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.staff_id
     *
     * @return the value of staff_terminal.staff_id
     * @mbg.generated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.staff_id
     *
     * @param staffId the value for staff_terminal.staff_id
     * @mbg.generated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.terminal_id
     *
     * @return the value of staff_terminal.terminal_id
     * @mbg.generated
     */
    public Integer getTerminalId() {
        return terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.terminal_id
     *
     * @param terminalId the value for staff_terminal.terminal_id
     * @mbg.generated
     */
    public void setTerminalId(Integer terminalId) {
        this.terminalId = terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.create_time
     *
     * @return the value of staff_terminal.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.create_time
     *
     * @param createTime the value for staff_terminal.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.model_number
     *
     * @return the value of staff_terminal.model_number
     * @mbg.generated
     */
    public String getModelNumber() {
        return modelNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.model_number
     *
     * @param modelNumber the value for staff_terminal.model_number
     * @mbg.generated
     */
    public void setModelNumber(String modelNumber) {
        this.modelNumber = modelNumber == null ? null : modelNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.hardware_version
     *
     * @return the value of staff_terminal.hardware_version
     * @mbg.generated
     */
    public String getHardwareVersion() {
        return hardwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.hardware_version
     *
     * @param hardwareVersion the value for staff_terminal.hardware_version
     * @mbg.generated
     */
    public void setHardwareVersion(String hardwareVersion) {
        this.hardwareVersion = hardwareVersion == null ? null : hardwareVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.software_version
     *
     * @return the value of staff_terminal.software_version
     * @mbg.generated
     */
    public String getSoftwareVersion() {
        return softwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.software_version
     *
     * @param softwareVersion the value for staff_terminal.software_version
     * @mbg.generated
     */
    public void setSoftwareVersion(String softwareVersion) {
        this.softwareVersion = softwareVersion == null ? null : softwareVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.co
     *
     * @return the value of staff_terminal.co
     * @mbg.generated
     */
    public Integer getCo() {
        return co;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.co
     *
     * @param co the value for staff_terminal.co
     * @mbg.generated
     */
    public void setCo(Integer co) {
        this.co = co;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.co_desc
     *
     * @return the value of staff_terminal.co_desc
     * @mbg.generated
     */
    public String getCoDesc() {
        return coDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.co_desc
     *
     * @param coDesc the value for staff_terminal.co_desc
     * @mbg.generated
     */
    public void setCoDesc(String coDesc) {
        this.coDesc = coDesc == null ? null : coDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.o2
     *
     * @return the value of staff_terminal.o2
     * @mbg.generated
     */
    public Integer getO2() {
        return o2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.o2
     *
     * @param o2 the value for staff_terminal.o2
     * @mbg.generated
     */
    public void setO2(Integer o2) {
        this.o2 = o2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.o2_desc
     *
     * @return the value of staff_terminal.o2_desc
     * @mbg.generated
     */
    public String getO2Desc() {
        return o2Desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.o2_desc
     *
     * @param o2Desc the value for staff_terminal.o2_desc
     * @mbg.generated
     */
    public void setO2Desc(String o2Desc) {
        this.o2Desc = o2Desc == null ? null : o2Desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.ch4
     *
     * @return the value of staff_terminal.ch4
     * @mbg.generated
     */
    public Integer getCh4() {
        return ch4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.ch4
     *
     * @param ch4 the value for staff_terminal.ch4
     * @mbg.generated
     */
    public void setCh4(Integer ch4) {
        this.ch4 = ch4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.ch4_desc
     *
     * @return the value of staff_terminal.ch4_desc
     * @mbg.generated
     */
    public String getCh4Desc() {
        return ch4Desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.ch4_desc
     *
     * @param ch4Desc the value for staff_terminal.ch4_desc
     * @mbg.generated
     */
    public void setCh4Desc(String ch4Desc) {
        this.ch4Desc = ch4Desc == null ? null : ch4Desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.voice
     *
     * @return the value of staff_terminal.voice
     * @mbg.generated
     */
    public Integer getVoice() {
        return voice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.voice
     *
     * @param voice the value for staff_terminal.voice
     * @mbg.generated
     */
    public void setVoice(Integer voice) {
        this.voice = voice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.voice_desc
     *
     * @return the value of staff_terminal.voice_desc
     * @mbg.generated
     */
    public String getVoiceDesc() {
        return voiceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.voice_desc
     *
     * @param voiceDesc the value for staff_terminal.voice_desc
     * @mbg.generated
     */
    public void setVoiceDesc(String voiceDesc) {
        this.voiceDesc = voiceDesc == null ? null : voiceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.wifi
     *
     * @return the value of staff_terminal.wifi
     * @mbg.generated
     */
    public Integer getWifi() {
        return wifi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.wifi
     *
     * @param wifi the value for staff_terminal.wifi
     * @mbg.generated
     */
    public void setWifi(Integer wifi) {
        this.wifi = wifi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.wifi_desc
     *
     * @return the value of staff_terminal.wifi_desc
     * @mbg.generated
     */
    public String getWifiDesc() {
        return wifiDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.wifi_desc
     *
     * @param wifiDesc the value for staff_terminal.wifi_desc
     * @mbg.generated
     */
    public void setWifiDesc(String wifiDesc) {
        this.wifiDesc = wifiDesc == null ? null : wifiDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.battery
     *
     * @return the value of staff_terminal.battery
     * @mbg.generated
     */
    public Integer getBattery() {
        return battery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.battery
     *
     * @param battery the value for staff_terminal.battery
     * @mbg.generated
     */
    public void setBattery(Integer battery) {
        this.battery = battery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_terminal.battery_desc
     *
     * @return the value of staff_terminal.battery_desc
     * @mbg.generated
     */
    public String getBatteryDesc() {
        return batteryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_terminal.battery_desc
     *
     * @param batteryDesc the value for staff_terminal.battery_desc
     * @mbg.generated
     */
    public void setBatteryDesc(String batteryDesc) {
        this.batteryDesc = batteryDesc == null ? null : batteryDesc.trim();
    }
}
