package com.zkxh.demo.dao.staff;

import com.zkxh.demo.model.staff.StaffTerminal;
import com.zkxh.demo.model.staff.StaffTerminalExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface StaffTerminalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal
     *
     * @mbg.generated
     */
    long countByExample(StaffTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal
     *
     * @mbg.generated
     */
    int deleteByExample(StaffTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer staffTerminalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal
     *
     * @mbg.generated
     */
    int insert(StaffTerminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal
     *
     * @mbg.generated
     */
    int insertSelective(StaffTerminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal
     *
     * @mbg.generated
     */
    List<StaffTerminal> selectByExample(StaffTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal
     *
     * @mbg.generated
     */
    StaffTerminal selectByPrimaryKey(Integer staffTerminalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StaffTerminal record, @Param("example") StaffTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StaffTerminal record, @Param("example") StaffTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StaffTerminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StaffTerminal record);
}