package com.zkxh.demo.dao.teminal_road;

import com.zkxh.demo.model.teminal_road.TeminalRoad;
import com.zkxh.demo.model.teminal_road.TeminalRoadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeminalRoadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teminal_road
     *
     * @mbg.generated
     */
    long countByExample(TeminalRoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teminal_road
     *
     * @mbg.generated
     */
    int deleteByExample(TeminalRoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teminal_road
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer teminalRoadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teminal_road
     *
     * @mbg.generated
     */
    int insert(TeminalRoad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teminal_road
     *
     * @mbg.generated
     */
    int insertSelective(TeminalRoad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teminal_road
     *
     * @mbg.generated
     */
    List<TeminalRoad> selectByExample(TeminalRoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teminal_road
     *
     * @mbg.generated
     */
    TeminalRoad selectByPrimaryKey(Integer teminalRoadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teminal_road
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TeminalRoad record, @Param("example") TeminalRoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teminal_road
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TeminalRoad record, @Param("example") TeminalRoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teminal_road
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TeminalRoad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teminal_road
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeminalRoad record);
}