package com.zkxh.demo.dao.part;

import com.zkxh.demo.model.part.Part;
import com.zkxh.demo.model.part.PartExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbg.generated
     */
    long countByExample(PartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbg.generated
     */
    int deleteByExample(PartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbg.generated
     */
    int insert(Part record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbg.generated
     */
    int insertSelective(Part record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbg.generated
     */
    List<Part> selectByExample(PartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbg.generated
     */
    Part selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Part record, @Param("example") PartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Part record, @Param("example") PartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Part record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Part record);

    List<Part> selectAll();


}