package com.zkxh.demo.model.teminal_road;

import java.util.Date;

public class TeminalRoad {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teminal_road.teminal_road_id
     *
     * @mbg.generated
     */
    private Integer teminalRoadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teminal_road.staff_teminal_id
     *
     * @mbg.generated
     */
    private Integer staffTeminalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teminal_road.position_x
     *
     * @mbg.generated
     */
    private Double positionX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teminal_road.position_y
     *
     * @mbg.generated
     */
    private Double positionY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teminal_road.position_z
     *
     * @mbg.generated
     */
    private Double positionZ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teminal_road.station_id1
     *
     * @mbg.generated
     */
    private Integer stationId1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teminal_road.station_id2
     *
     * @mbg.generated
     */
    private Integer stationId2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teminal_road.wifi_strength1
     *
     * @mbg.generated
     */
    private Double wifiStrength1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teminal_road.wifi_strength2
     *
     * @mbg.generated
     */
    private Double wifiStrength2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teminal_road.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teminal_road.teminal_road_id
     *
     * @return the value of teminal_road.teminal_road_id
     *
     * @mbg.generated
     */
    public Integer getTeminalRoadId() {
        return teminalRoadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teminal_road.teminal_road_id
     *
     * @param teminalRoadId the value for teminal_road.teminal_road_id
     *
     * @mbg.generated
     */
    public void setTeminalRoadId(Integer teminalRoadId) {
        this.teminalRoadId = teminalRoadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teminal_road.staff_teminal_id
     *
     * @return the value of teminal_road.staff_teminal_id
     *
     * @mbg.generated
     */
    public Integer getStaffTeminalId() {
        return staffTeminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teminal_road.staff_teminal_id
     *
     * @param staffTeminalId the value for teminal_road.staff_teminal_id
     *
     * @mbg.generated
     */
    public void setStaffTeminalId(Integer staffTeminalId) {
        this.staffTeminalId = staffTeminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teminal_road.position_x
     *
     * @return the value of teminal_road.position_x
     *
     * @mbg.generated
     */
    public Double getPositionX() {
        return positionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teminal_road.position_x
     *
     * @param positionX the value for teminal_road.position_x
     *
     * @mbg.generated
     */
    public void setPositionX(Double positionX) {
        this.positionX = positionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teminal_road.position_y
     *
     * @return the value of teminal_road.position_y
     *
     * @mbg.generated
     */
    public Double getPositionY() {
        return positionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teminal_road.position_y
     *
     * @param positionY the value for teminal_road.position_y
     *
     * @mbg.generated
     */
    public void setPositionY(Double positionY) {
        this.positionY = positionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teminal_road.position_z
     *
     * @return the value of teminal_road.position_z
     *
     * @mbg.generated
     */
    public Double getPositionZ() {
        return positionZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teminal_road.position_z
     *
     * @param positionZ the value for teminal_road.position_z
     *
     * @mbg.generated
     */
    public void setPositionZ(Double positionZ) {
        this.positionZ = positionZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teminal_road.station_id1
     *
     * @return the value of teminal_road.station_id1
     *
     * @mbg.generated
     */
    public Integer getStationId1() {
        return stationId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teminal_road.station_id1
     *
     * @param stationId1 the value for teminal_road.station_id1
     *
     * @mbg.generated
     */
    public void setStationId1(Integer stationId1) {
        this.stationId1 = stationId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teminal_road.station_id2
     *
     * @return the value of teminal_road.station_id2
     *
     * @mbg.generated
     */
    public Integer getStationId2() {
        return stationId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teminal_road.station_id2
     *
     * @param stationId2 the value for teminal_road.station_id2
     *
     * @mbg.generated
     */
    public void setStationId2(Integer stationId2) {
        this.stationId2 = stationId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teminal_road.wifi_strength1
     *
     * @return the value of teminal_road.wifi_strength1
     *
     * @mbg.generated
     */
    public Double getWifiStrength1() {
        return wifiStrength1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teminal_road.wifi_strength1
     *
     * @param wifiStrength1 the value for teminal_road.wifi_strength1
     *
     * @mbg.generated
     */
    public void setWifiStrength1(Double wifiStrength1) {
        this.wifiStrength1 = wifiStrength1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teminal_road.wifi_strength2
     *
     * @return the value of teminal_road.wifi_strength2
     *
     * @mbg.generated
     */
    public Double getWifiStrength2() {
        return wifiStrength2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teminal_road.wifi_strength2
     *
     * @param wifiStrength2 the value for teminal_road.wifi_strength2
     *
     * @mbg.generated
     */
    public void setWifiStrength2(Double wifiStrength2) {
        this.wifiStrength2 = wifiStrength2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teminal_road.createTime
     *
     * @return the value of teminal_road.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teminal_road.createTime
     *
     * @param createtime the value for teminal_road.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}